- README.md
- build.sbt
- demo/greeting/src/main/scala/greeting/GreetingClientApp.scala
- demo/greeting/src/main/scala/greeting/GreetingServerApp.scala
- demo/greeting/src/main/scala/greeting/runtime/implicits.scala
- demo/http/src/main/scala/user/UserClientApp.scala
- demo/http/src/main/scala/user/UserServerApp.scala
- demo/http/src/main/scala/user/runtime/implicits.scala
- rpc/src/main/scala/server/GrpcConfig.scala
- rpc/src/main/scala/server/GrpcServer.scala
- rpc/src/main/scala/server/handlers/GrpcServerHandler.scala
- rpc/src/main/scala/server/implicits.scala
- rpc/src/main/scala/server/package.scala
Server Demo has been also adapted to the newly introduced changes, where the RPC core provides helpers in order to bootstrap the server in the runtime monad, according to the server configuration.
This is a preliminary version towards to fulfill https://github.com/frees-io/freestyle-rpc/issues/10. We still need to find the way to aggregate all the services which would run in such a server.
For now, the user has to provide an implicit list with all the services the server will register:
https://github.com/frees-io/freestyle-rpc/compare/feature/server-definitions#diff-09bc282791d5598d8a70f248fbb125b0R33
Thanks @peterneyens for your suggestions related to the `GrpcConfigInterpreter` :)
Server bootstrap:
```scala
import cats.implicits._
import runtime.implicits._
import freestyle.rpc.server._ …
```
> Provides grpc configuration DSL and GrpcServer algebras

- demo/greeting/src/main/proto/echo.proto
- demo/greeting/src/main/proto/echo_messages.proto
- demo/greeting/src/main/scala/greeting/GreetingClientApp.scala
- demo/greeting/src/main/scala/greeting/runtime/implicits.scala
- demo/greeting/src/main/scala/greeting/service/EchoService.scala
- demo/greeting/src/main/scala/greeting/service/GreetingService.scala
- rpc/src/main/scala/server/package.scala
... to combine different services in both server and client sides.
> Provides a Demo Extension

- build.sbt
- demo/greeting/src/main/scala/greeting/GreetingClient.scala
- demo/greeting/src/main/scala/greeting/GreetingClientApp.scala
- demo/greeting/src/main/scala/greeting/GreetingServerApp.scala
- demo/greeting/src/main/scala/greeting/client/EchoClientM.scala
- demo/greeting/src/main/scala/greeting/client/GreetingClientM.scala
- demo/greeting/src/main/scala/greeting/runtime/implicits.scala
- rpc/src/main/scala/client/ChannelConfig.scala
- rpc/src/main/scala/client/ChannelM.scala
- rpc/src/main/scala/client/ClientCallsM.scala
- rpc/src/main/scala/client/handlers/ChannelMHandler.scala
- rpc/src/main/scala/client/handlers/ClientCallsMHandler.scala
- rpc/src/main/scala/client/implicits.scala
- rpc/src/main/scala/client/package.scala
- rpc/src/main/scala/server/GrpcConfig.scala
- rpc/src/main/scala/server/implicits.scala
- rpc/src/main/scala/server/package.scala
This PR solves partially the issue https://github.com/frees-io/freestyle-rpc/issues/11  (only unary services).
It brings some free algebras on top of Grpc for RPC clients. Concretely, it solves:
* Channel Configuration.
* Channel Algebra to be able to create new RPC calls, based on method descriptors and some call options.
* ClientCalls Algebra to perform the different types of calls (unary, client streaming, server streaming and bidirecctional).
It also updates the demo code to use these algebras, composing RPC services as freestyle modules:
```scala
@module
trait ClientAPP {
val greetingClientM: GreetingClientM
val echoClientM: EchoClientM
}
object GreetingClientApp {
val messageRequest = MessageRequest("Freestyle")
val echoRequest    = EchoRequest("echo...")
def …
```
> Client Definitions based on free algebras - Unary Services 

- build.sbt
- project/ProjectPlugin.scala
- rpc/src/main/scala/client/ChannelConfig.scala
- rpc/src/main/scala/server/implicits.scala
- rpc/src/test/scala/server/GrpcServerTests.scala
- rpc/src/test/scala/server/HelperTests.scala
- rpc/src/test/scala/server/RpcTestSuite.scala
- rpc/src/test/scala/server/handlers/GrpcServerHandlerTests.scala
This PR adds some tests over server definitions (related to #15).
> Server Definitions - Test Coverage

- demo/greeting/src/main/scala/greeting/runtime/implicits.scala
- demo/http/src/main/scala/user/runtime/implicits.scala
- rpc/src/main/scala/server/GrpcConfig.scala
- rpc/src/main/scala/server/ServerConfig.scala
- rpc/src/main/scala/server/package.scala
- rpc/src/test/resources/application.conf
- rpc/src/test/scala/server/RpcTestSuite.scala
- rpc/src/test/scala/server/ServerConfigTests.scala
- rpc/src/test/scala/server/SyntaxTests.scala
This PR completes https://github.com/frees-io/freestyle-rpc/issues/15
Now, rpc server module reaches almost the 100% of test coverage. In the next PRs I'll cover the client definition tests.
Please, @fedefernandez could you take a look? Thanks!
> Adds additional server definitions tests

- rpc/src/test/scala/RpcBaseTestSuite.scala
- rpc/src/test/scala/client/ConversionsTests.scala
- rpc/src/test/scala/client/RpcClientTestSuite.scala
- rpc/src/test/scala/client/handlers/ChannelHandlerTests.scala
- rpc/src/test/scala/client/utils/marshallers.scala
- rpc/src/test/scala/server/GrpcServerTests.scala
- rpc/src/test/scala/server/RpcServerTestSuite.scala
- rpc/src/test/scala/server/ServerConfigTests.scala
- rpc/src/test/scala/server/SyntaxTests.scala
- rpc/src/test/scala/server/handlers/GrpcServerHandlerTests.scala
Also, restructures the test suite classes to use them across client and server tests.
Related to #24
> Adds tests for some client handlers

- build.sbt
- demo/protocolgen/src/main/proto/service.proto
- demo/protocolgen/src/main/scala/Client.scala
- demo/protocolgen/src/main/scala/ClientApp.scala
- demo/protocolgen/src/main/scala/ServerApp.scala
- demo/protocolgen/src/main/scala/runtime/implicits.scala
- demo/protocolgen/src/main/scala/service.scala
- project/ProjectPlugin.scala
- rpc/src/main/scala/ProtoCodeGen.scala
- rpc/src/main/scala/internal/service/GRPCServiceDefBuilder.scala
- rpc/src/main/scala/internal/service/StreamingMethods.scala
- rpc/src/main/scala/internal/service/service.scala
- rpc/src/main/scala/proto/annotations.scala
- rpc/src/main/scala/proto/converters.scala
Fixes #29 
Generates valid service description for a @free annotated macro with the proto annotations.
```scala
@free
@service
@debug
trait GreetingService {
@rpc def sayHello(msg: MessageRequest): FS[MessageReply]
@rpc
@stream[ResponseStreaming.type]
def lotsOfReplies(msg: MessageRequest, observer: StreamObserver[MessageReply]): FS[Unit]
@rpc
@stream[RequestStreaming.type]
def lotsOfGreetings(msg: StreamObserver[MessageReply]): FS[StreamObserver[MessageRequest]]
@rpc
@stream[BidirectionalStreaming.type]
def bidiHello(msg: StreamObserver[MessageReply]): FS[StreamObserver[MessageRequest]]
}
```
Allows you to:
```scala
def grpcConfigs[M[_]](implicit ME: MonadError[M, Throwable]): List[GrpcConfig] = List(
AddService(GreetingService.bindService[GreetingService.Op, M])
)
```
> @service Macro

- demo/protocolgen/src/main/scala/ClientApp.scala
- demo/protocolgen/src/main/scala/runtime/implicits.scala
- rpc/src/main/scala/internal/MonixAdapters.scala
- rpc/src/main/scala/internal/service/calls.scala
- rpc/src/main/scala/internal/service/service.scala
This PR completes the basic example we've been playing with. It brings some fixes and makes both server and client streaming working with Monix observables.
We're now ready for https://github.com/frees-io/freestyle-rpc/issues/34.
> Completes the basic Example

- README.md
- build.sbt
- version.sbt
Fixes https://github.com/frees-io/freestyle-rpc/issues/38
It also releases the first release (0.0.1) of `freestyle-rpc` giving some tiny instructions about how to use it.
> Upgrades gRPC. Releases frees-rpc 0.0.1.

- rpc/src/main/scala/proto/converters.scala
`Type.Arg` within the input parameters are optional (`Option[scala.meta.Type.Arg]`). Hence, `toString` method was printing the file with the existential type. For example:
```
message CustomType2 {
string foo = 1;
Some(CustomType1) bar = 2;
}
```
This fix comes to solve it, making the output as follows:
```
message CustomType2 {
string foo = 1;
CustomType1 bar = 2;
}
```
> Bug Fix  Proto Code Generator for Custom Types

- rpc/src/main/scala/proto/converters.scala
This PR fixes list types as `repeated` (for custom types) in the generated proto files.
```scala
case class Foo(bar: List[CustomType])
```
Results as:
```
message Foo {
repeated CustomType bar = 1;
}
```
> Fixes proto code generator for repeated types

- rpc/src/main/scala/client/package.scala
This PR removes the unnecessary `private` modifier for the `Channel` build method.
@vejeta ^^
> Makes the ChannelBuilder build a public method

- rpc/src/main/scala/internal/service/calls.scala
- rpc/src/main/scala/internal/service/service.scala
- version.sbt
Regarding the `ClientStreaming` mode, this PR replaces the `Comonad` implicit dependency by a simple Natural Transformation to go from `M` to `Task`, since it's the more simplest way to create the `Transformer` function, which actually is a:
```scala
/** A `Transformer` is a function used for transforming observables */
type Transformer[-A,+B] = Observable[A] => Observable[B]
```
> Fixes Client Streaming rpc server

- .travis.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
- rpc/src/main/scala/client/package.scala
- rpc/src/test/scala/client/RpcClientTestSuite.scala
It also updates the `build.sbt` in order to use entirely the `sbt-org-policies` DSL to inject dependencies.
> Upgrades to sbt 1.0.1 and Scala 2.12.3

- build.sbt
- rpc/src/main/scala/internal/service/service.scala
- rpc/src/main/scala/proto/annotations.scala
- rpc/src/test/scala/client/ImplicitTests.scala
- rpc/src/test/scala/client/RpcClientTestSuite.scala
- rpc/src/test/scala/client/handlers/TaskMHandlerTests.scala
Partially solves https://github.com/frees-io/freestyle-rpc/issues/24
It disables coverage for macros and annotations.
> Test Coverage for some client definitions

- build.sbt
- rpc/src/main/scala/AsyncInstances.scala
- rpc/src/main/scala/client/implicits.scala
- rpc/src/main/scala/server/implicits.scala
- rpc/src/test/scala/Utils.scala
- rpc/src/test/scala/client/ImplicitTests.scala
- version.sbt
This PR groups the set of async common instances (`Future`, `Task`) into the `AsyncInstances` trait. Then these implicits are provided for both `server` and `client` implicit imports:
`import freestyle.rpc.server.implicits._` or `import freestyle.rpc.client.implicits._`.
Fixes #70 
Fixes #66
> Groups async implicits into AsyncInstances trait

- rpc/src/main/scala/proto/annotations.scala
- rpc/src/test/scala/FreesRPCTests.scala
- rpc/src/test/scala/Utils.scala
As Protobuf provides [Emtpy](https://github.com/google/protobuf/blob/master/src/google/protobuf/empty.proto), this PR provides an empty type: `freestyle.rpc.protocol.Empty` as generic empty message that you can re-use to avoid defining duplicated empty messages in your APIs. A typical example is to use it as the request or the response type of an API method.
For instance:
```scala
@free
@service
trait Foo {      
@rpc def Bar(empty: Empty): FS[Empty]      
}
```
Fixes #63
> Provides Empty Message

- rpc/src/main/scala/internal/service/service.scala
- rpc/src/test/scala/client/RpcClientTestSuite.scala
Fixes https://github.com/frees-io/freestyle-rpc/issues/69
> Updates macros to avoid deprecation warnings

- README.md
- version.sbt
This PR releases `frees-rpc` **0.2.0**.
This new version would include the following features:
* #74: Upgrades to `gRPC` 1.7.0.
* #75: Updates macros to avoid deprecation warnings.
* #76: Provides Empty Message.
It also modifies the `README.md` file with additional notes.
> Releases 0.2.0

- build.sbt
- common/src/main/scala/protocol.scala
- rpc/src/main/scala/internal/service/service.scala
- rpc/src/main/scala/proto/annotations.scala
- rpc/src/test/scala/Utils.scala
- rpc/src/test/scala/server/GrpcServerTests.scala
This PR brings support for Avro serialization.
Therefore, from now on, you can choose for your service (at `@rpc` level) the type of serialization. Currently: `Avro` or `Protobuf`.
```scala
@free
@service
trait FreesRPCService {
@rpc(Avro) def unary(a: A): FS[C]
@rpc(Protobuf)
@stream[ResponseStreaming.type]
def serverStreaming(b: B): FS[Observable[C]]
@rpc(Protobuf)
@stream[RequestStreaming.type]
def clientStreaming(oa: Observable[A]): FS[D]
@rpc(Avro)
@stream[BidirectionalStreaming.type]
def biStreaming(oe: Observable[E]): FS[Observable[E]]
}
```
We are relying on [avro4s](https://github.com/sksamuel/avro4s) for the binary serialization/deserialization.
> Support for Avro Serialization

- build.sbt
- rpc/src/main/scala/RPCAsyncImplicits.scala
- rpc/src/main/scala/client/implicits.scala
- rpc/src/main/scala/server/implicits.scala
- rpc/src/test/scala/FreesRPCTests.scala
- rpc/src/test/scala/Utils.scala
- rpc/src/test/scala/client/ImplicitTests.scala
In order to simplify the use of `frees-rpc`, this PR makes that server and client implicits provide automatically:
* `import freestyle.implicits._`
* `import freestyle.async.implicits._`
Hence, users only need to import either:
* `import freestyle.rpc.client.implicits._`
* `import freestyle.rpc.server.implicits._`
> Async Implicits provided by frees-rpc Implicits

- version.sbt
It includes breaking features, given that from now on, the `@rpc` annotation requires the type of serialization (either `Protobuf` or `Avro`).
> Releases 0.3.0

- rpc/src/main/scala/internal/service/service.scala
- version.sbt
This PR suppresses wart warnings in the code generated by scalameta, related to default arguments and nulls.
> Suppress wart warnings

- rpc/src/main/scala/internal/service/service.scala
- rpc/src/main/scala/proto/annotations.scala
- rpc/src/test/scala/FreesRPCTests.scala
- rpc/src/test/scala/Utils.scala
It solves #86 #79 
Finally I added the param `s: String = ""` to the existing case class and I created several test for it
> Case class Empty is valid for Avro as well

- build.sbt
- project/build.properties
- rpc/src/main/scala/internal/service/service.scala
- version.sbt
This PR adds some FQFN within the `@service` macro. It also:
* Upgrades to freestyle **0.4.4**.
* Releases a new patch release: **0.3.3**.
> Fixes missing FQFN

- rpc/src/main/scala/RPCAsyncImplicits.scala
- version.sbt
It also releases a new patch version: `0.3.4`.
> Adds monix.eval.Task Comonad Implicit Evidence

- .travis.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
- version.sbt
It also releases a new minor version: `0.4.0`, since we are releasing the new features done by @tbrown1979 in this PR https://github.com/frees-io/freestyle-rpc/pull/92 .
> Upgrades frees-rpc to Freestyle 0.4.6

- build.sbt
- rpc/src/main/scala/RPCAsyncImplicits.scala
- rpc/src/main/scala/internal/service/calls.scala
- rpc/src/main/scala/internal/service/service.scala
- rpc/src/main/scala/server/implicits.scala
- rpc/src/test/scala/TaglessUtils.scala
- rpc/src/test/scala/Utils.scala
- version.sbt
Until now, especially the unary endpoint was being executed based on the `apply` method, hence only `scala.concurrent.Future` was a valid Monad for the Server interpretation.
This PR fixes this issue requesting a `cats.effect.Effect` instance in order to be able to suspend all the side effects into the `F` context. Therefore, the servers that currently are interpreting to `scala.concurrent.Future` could move interpreting to `cats.effect.IO`, and then, they can still use the `unsafeToFuture` method in order to evaluate the effect and produce the result in a `scala.concurrent.Future`.
However, the new servers can now interpret to suspendable Monads, like the mentioned `cats.effect.IO` or `monix.eval.Task`.
There are two additional task implemented in this PR:
* Async Instances grouping …
> Server Endpoints and Effect Monad

- rpc/src/main/scala/internal/service/service.scala
- rpc/src/test/scala/TaglessUtils.scala
- rpc/src/test/scala/Utils.scala
This PR reduces some boilerplate when creating RPC client instances:
Previously to this change, in order to create new client instances, users have to do something like the following:
```scala
import cats.effect.IO
import freestyle.rpc.client._
import io.grpc.ManagedChannel //notice a io.grpc.import
val channelFor: ManagedChannelFor = ManagedChannelForAddress("localhost", 8080)
val channelConfigList: List[ManagedChannelConfig] = List(UsePlaintext(true))
val managedChannelInterpreter =
new ManagedChannelInterpreter[IO](channelFor, channelConfigList)
val channel: ManagedChannel = managedChannelInterpreter.build(channelFor, channelConfigList)
val client: YourService.Client[IO] = YourService.client[IO](channel)
```
After this change, `channelConfigList` would be optional since it has a …
> Reduces boilerplate when creating client instances

- rpc/src/main/scala/internal/service/service.scala
- rpc/src/test/scala/Utils.scala
- rpc/src/test/scala/models.scala
- version.sbt
This PR makes possible to have inner imports within the annotated @service trait:
```scala
@service
trait RPCService[F[_]] {
import ExternalScope._
@rpc(Protobuf)
def scope(empty: Empty.type): F[External]
}
```
It also releases a new patch version -> **0.5.1**.
> Supports inner imports within @service macro.

- build.sbt
- version.sbt
This PR makes that frees-rpc only relies on the gRPC guava version, that by these days, it's the `19.0`.
> Excludes Guava from frees-async-guava

- .travis.yml
- build.sbt
- docs/src/main/tut/README.md
- version.sbt
Documentation comes from https://github.com/frees-io/freestyle/blob/master/docs/src/main/tut/docs/rpc/README.md, which will be removed very soon in favor of using this one.
The current `orgScriptCI` sbt task will check the docs in Travis.
Related to: https://github.com/frees-io/freestyle/pull/483
> Compiled docs in frees-rpc repo

- docs/src/main/tut/README.md
Added a simple text and example where I try to explain that we can return an empty content as response in RPC service
It resolves https://github.com/frees-io/freestyle/issues/457
> Docs - Empty.type Request/Response

- modules/config/src/main/scala/client/ChannelConfig.scala
- modules/config/src/main/scala/server/ServerConfig.scala
- modules/internal/src/main/scala/server/calls.scala
- modules/server/src/main/scala/implicits.scala
- modules/server/src/test/scala/CommonUtils.scala
- modules/server/src/test/scala/server/GrpcServerTests.scala
Were the `S.getPort` there from when frees-rpc did logging? Could those be removed now that is no longer the case?
> Mini cleanup after move to finally tagless

- docs/src/main/tut/README.md
- modules/internal/src/main/scala/client/calls.scala
- modules/server/src/test/scala/withouttagless/Utils.scala
- modules/server/src/test/scala/withtagless/TaglessUtils.scala
- project/ProjectPlugin.scala
- version.sbt
This PR upgrades to the latest version of Freestyle: `0.6.1`, as it includes some breaking changes since version 0.5.3, so it also releases a new minor version of `frees-rpc`: **0.9.0**.
> Upgrades to Freestyle 0.6.1. Releases 0.9.0.

- build.sbt
- modules/interceptors/src/main/scala/GrpcMethodInfo.scala
- modules/interceptors/src/main/scala/implicits.scala
- modules/prometheus/server/src/main/scala/MonitoringServerInterceptor.scala
- modules/prometheus/server/src/main/scala/ServerMetrics.scala
- modules/prometheus/server/src/main/scala/ServerMetricsForMethod.scala
- modules/prometheus/server/src/test/scala/InterceptorsRuntime.scala
- modules/prometheus/server/src/test/scala/MonitorServerInterceptorTests.scala
- modules/prometheus/server/src/test/scala/RegistryHelper.scala
- modules/prometheus/shared/src/main/scala/Configuration.scala
- modules/server/src/test/scala/CommonUtils.scala
- modules/server/src/test/scala/withouttagless/Utils.scala
- modules/server/src/test/scala/withtagless/TaglessUtils.scala
- project/ProjectPlugin.scala
This PR adds some new optional artifacts that you might want to add to your build in order to monitor your `gRPC` services.
Concretely, adding:
```
libraryDependencies += "io.frees" %% "frees-rpc-prometheus-server" % "x.y.z"
```
Your RPC services will be able to intercept every RPC call on the server side and collect metrics that you could render in your dashboard, using [Prometheus](https://prometheus.io/).
Adding services without intercepting calls:
```scala
lazy val grpcConfigs: List[GrpcConfig] = List(
AddService(RPCService.bindService[ConcurrentMonad])
)
```
Intercepting calls with [Prometheus](https://prometheus.io/):
```scala
import freestyle.rpc.interceptors.implicits._
lazy val cr: CollectorRegistry = new CollectorRegistry()
lazy val monitorInterceptor = …
```
> gRPC Services Metrics using Prometheus

- modules/interceptors/src/main/scala/metrics.scala
- modules/prometheus/client/src/main/scala/ClientMetrics.scala
- modules/prometheus/client/src/test/scala/MonitorClientInterceptorTests.scala
- modules/prometheus/server/src/main/scala/ServerMetrics.scala
- modules/prometheus/server/src/test/scala/MonitorServerInterceptorTests.scala
- modules/prometheus/shared/src/main/scala/implicits.scala
- modules/prometheus/shared/src/test/scala/RegistryHelper.scala
After #138 and #139 , this PR brings some code improvements in order to be able to re-utilize all the metrics for Prometheus for any other monitoring tool.
It adds a micro-DSL to store these metrics and provide syntax helpers to build the existing ones easily. All the hardcoded metrics in the tests have been replaced by using these enhancements.
> Metrics DSL

- build.sbt
- project/ProjectPlugin.scala
This PR adds a new sbt module (artifact `frees-rpc-testing`) to provide transitively the `grpc-testing` dependency. In this way, library users don't need to know which is the `gRPC` version underneath.
> Adds *frees-rpc-testing* including *grpc-testing* dependency

- modules/dropwizard/client/src/test/scala/MonitorClientInterceptorTests.scala
- modules/prometheus/client/src/test/scala/BaseMonitorClientInterceptorTests.scala
- modules/prometheus/client/src/test/scala/InterceptorsRuntime.scala
- modules/prometheus/client/src/test/scala/MonitorClientInterceptorTests.scala
- modules/prometheus/server/src/test/scala/BaseMonitorServerInterceptorTests.scala
This PR enforces that all the metrics tests (for both server and client), sequentially does (for every test fragment):
* Start the server
* Request/s
* Stop the server
In this way, the random tests failures are gone after 12 successful builds in Travis (bearing in mind Scala 2.11 and Scala 2.12).
> Monadic Server Start/RPC Calls/Stop in Tests

- modules/common/src/test/scala/RpcBaseTestSuite.scala
- modules/common/src/test/scala/common.scala
- modules/prometheus/client/src/test/scala/BaseMonitorClientInterceptorTests.scala
The latest changes have been passed on Travis (14 builds in total)
> Fixes random test failure

- README.md
- docs/src/main/tut/README.md
And also adds an extra-table explaining all the available modules.
> Updates Docs regarding Metrics Reporting

- project/ProjectPlugin.scala
- version.sbt
It also bumps up the freestyle version to `0.6.2`.
> Releases *frees-rpc* 0.10.0

- modules/common/src/test/scala/RpcBaseTestSuite.scala
- modules/common/src/test/scala/common.scala
- modules/prometheus/client/src/test/scala/BaseMonitorClientInterceptorTests.scala
Fixes the random test failure by retrying the *completed* metrics check until a max retry is reached or the check pass.
> Try to fix the random test failure in client metrics

- modules/internal/src/main/scala/MonixAdapters.scala
- modules/internal/src/main/scala/client/package.scala
- modules/internal/src/main/scala/server/fs2Calls.scala
- modules/internal/src/main/scala/server/monixCalls.scala
- modules/internal/src/main/scala/server/package.scala
Small `internal` cleanup
- Conversions between `StreamObserver` and Monix / reactive streams `Subscriber`s are now syntax methods instead of implicit conversions.
- Introduce `transformStreamObserver`.
> Change implicit StreamObserver conversions to syntax

- docs/src/main/tut/README.md
- modules/internal/src/main/scala/service.scala
- modules/server/src/test/scala/protocol/RPCTests.scala
- modules/server/src/test/scala/protocol/Utils.scala
This would allow for example to add helper methods to the `Client` which do some conversion from/to the RPC messages.
> Add non request statements to `Client`

- version.sbt
The biggest **frees-rpc** release so far is on its way:
* Update `gRPC` to 1.9.1 and other libs.
* SSL/TLS Encryption Support (Netty).
* Add non-request statements to `Client`.
* Allows adding compression at the method level.
* Refactor service macro.
* Change implicit StreamObserver conversions to syntax.
* fs2.Stream Support (Experimental API).
* Try to fix the random test failure in client metrics.
* Now the service requires an Effect instead of AsyncContext and `Task ~> M`.
* And much more.
Thanks @peterneyens, @fedefernandez for making this possible.
> Releases frees-rpc 0.11.0

- modules/internal/src/main/scala/service.scala
- modules/server/src/test/scala/fs2/Utils.scala
This brings back support for `@service` traits and abstract classes with an existing companion object.
> Readd support for companion objects

- .travis.yml
- build.sbt
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/.gitignore
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/build.sbt
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/project/plugins.sbt
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/src/main/scala/model.scala
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/test
- project/ProjectPlugin.scala
- project/plugins.sbt
This PR brings several things in order to fix the current sbt plugin once we've moved to the core:
* In Travis, we are building the Sbt Plugin in a different stage, preventing issues with the Scala 2.11 version.
* Loads scripted plugin only for Scala 2.12.
* Removes the plugin stuff from the core build. It should be built independently.
* Migrates the existing scripted tests from https://github.com/frees-io/sbt-freestyle-protogen/tree/master/src/sbt-test/sbt-freestyle-protogen to the plugin module.
* Plugin name has been renamed from `frees-rpc-sbt-idlgen` to `sbt-frees-rpc-idlgen`, following the pattern `sbt-whatever`, this is just a suggestion, let me know if it makes sense to you.
> Fixes Sbt Issues

- .travis.yml
- build.sbt
- docs/src/main/tut/README.md
- modules/idlgen/core/src/main/scala/ProtoCodeGen.scala
- modules/idlgen/core/src/main/scala/converters.scala
- modules/idlgen/core/src/main/scala/encoders.scala
- modules/idlgen/core/src/main/scala/model.scala
- modules/idlgen/core/src/main/scala/processors.scala
- modules/idlgen/core/src/test/proto/.gitignore
- modules/idlgen/core/src/test/proto/GreeterService_Expected.proto
- modules/idlgen/core/src/test/scala/GreeterService.scala
- modules/idlgen/core/src/test/scala/ProtoCodeGenTests.scala
- modules/idlgen/plugin/src/main/scala/ProtoGenPlugin.scala
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/.gitignore
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/build.sbt
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/project/plugins.sbt
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/src/main/scala/model.scala
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/test
- modules/internal/src/main/scala/service.scala
- project/ProjectPlugin.scala
- project/plugins.sbt
Resolves #180 and fixes https://github.com/frees-io/sbt-freestyle-protogen/issues/24. Note that this initial merge is mostly a straight-up copy of the current `sbt-freestyle-protogen` with different modules and package names, that removes the duplicated macro-processing code for `@rpc`-annotated methods and adds a basic unit test. There's still work to do on refactorings to be prepare for Avro gen, adding test coverage, and fixing some non-standard-compliant `.proto` output. (For the latter case I updated the readme to reflect what `protoGen` actually generates currently). Those remaining issues will be fixed in upcoming patches.
> Merge sbt-freestyle-protogen into freestyle-rpc codebase, and update @rpc processing to handle latest `freestyle-rpc syntax

- modules/client-netty/src/test/scala/ManagedChannelInterpreterNettyTests.scala
- modules/client/src/test/scala/ManagedChannelInterpreterTests.scala
- modules/server/src/test/scala/CommonUtils.scala
Also replaced `println` statement with logging, and fixed some grammar in tests.
> Fixed stacktraces in tests caused by unclosed channels

- build.sbt
- modules/http/server/src/main/scala/HttpConfig.scala
- modules/http/server/src/main/scala/HttpServerBuilder.scala
- modules/http/server/src/main/scala/HttpServerStream.scala
- modules/http/server/src/test/scala/ExampleService.scala
- modules/http/server/src/test/scala/HttpServerTests.scala
- project/ProjectPlugin.scala
Related to https://github.com/frees-io/freestyle-rpc/issues/182
This is a very beginning for supporting HTTP auto-derived endpoints from RPC protocols:
* Adds the new Sbt module for the HTTP server.
* Http config model.
* Adds a couple of helpers.
* Dummy tests for these helpers.
> Hello, Http Server integration

- docs/src/main/tut/core-concepts.md
- docs/src/main/tut/idl-generation.md
- modules/idlgen/core/src/main/scala/Application.scala
- modules/idlgen/core/src/main/scala/ProtoGenerator.scala
- modules/idlgen/core/src/test/resources/proto/GreeterService.proto
- modules/idlgen/core/src/test/scala/IdlGenTests.scala
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/.gitignore
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/test
- Fixes broken link in `.proto` headers and associated docs
- Fixes wrong `@option` statements in docs
- Adds `.avpr` generation to plugin test
- Misc testing and docs fixes
> Fixes in idlGen header, docs and tests

- modules/prometheus/client/src/test/scala/BaseMonitorClientInterceptorTests.scala
- modules/prometheus/server/src/test/scala/BaseMonitorServerInterceptorTests.scala
Workaround for #168.
Supersedes a previous commit to master (https://github.com/frees-io/freestyle-rpc/commit/54cb002e0f5fa59f544ba733866de629addb9254, reverted in https://github.com/frees-io/freestyle-rpc/commit/e987edeace886533cea33576e2a46bfab83f70bb) that fixed only one of the two failing tests.
> Ignore intermittently-failing tests on Travis

- .travis.yml
Just to make the simplest process first.
> Releases the plugin first, then the core

- modules/server/src/test/scala/avro/RPCTests.scala
- modules/server/src/test/scala/avro/Utils.scala
- modules/testing/src/test/scala/ServerChannel.scala
This PR solves some random issues at `freestyle.rpc.avro.RPCTests`, providing a new `ServerChannel` utility bringing the ability to bootstrap gRPC Servers using `InProcessServerBuilder`:
> Builder for a server that services in-process requests. Clients identify the in-process server by its name. The server is intended to be fully-featured, high performance, and useful in testing.
Related to #227
> Spins up gRPC Servers forName

- docs/src/main/tut/idl-generation.md
- modules/idlgen/core/src/main/scala/Generator.scala
- modules/idlgen/core/src/main/scala/GeneratorApplication.scala
- modules/idlgen/core/src/main/scala/IdlGenerator.scala
- modules/idlgen/core/src/main/scala/avro/AvroSrcGenerator.scala
- modules/idlgen/core/src/main/scala/idlgen.scala
- modules/idlgen/core/src/test/resources/avro/MyGreeterWithSchemaService.scala
- modules/idlgen/core/src/test/scala/SrcGenTests.scala
- modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/avroWithSchema/build.sbt
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/avroWithSchema/project/build.properties
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/avroWithSchema/project/plugins.sbt
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/avroWithSchema/src/main/resources/service.avdl
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/avroWithSchema/test
This PR adds support for `AvroWithSchema` serialization type, in the matter of IDL generation. 
Before this PR, only `Avro` was supported. Now, using the new Sbt setting `srcGenSerializationType`, the users can specify if the RPC services will be serializing with `Avro` or `AvroWithSchema` (actually, `AvroWithSchema` was included as part of https://github.com/frees-io/freestyle-rpc/pull/215, in this PR we are just providing the ability to generate Scala Sources based on that serialization type).
> SBT - Adds AvroWithSchema Support

- build.sbt
- modules/examples/routeguide/client/src/main/resources/application.conf
- modules/examples/routeguide/client/src/main/scala/ClientProgram.scala
- modules/examples/routeguide/client/src/main/scala/handlers/RouteGuideClientHandler.scala
- modules/examples/routeguide/client/src/main/scala/io/ClientAppIO.scala
- modules/examples/routeguide/client/src/main/scala/io/ClientIO.scala
- modules/examples/routeguide/client/src/main/scala/runtime/ClientConf.scala
- modules/examples/routeguide/client/src/main/scala/task/ClientAppTask.scala
- modules/examples/routeguide/client/src/main/scala/task/ClientTask.scala
This pr add the client module to the route guide example
The client module includes an IO and Task client with Freestyle-RPC
Fixes: #221
> Create example route guide client module

- modules/server/src/main/scala/handlers/GrpcServerHandler.scala
Before this PR, the shutdown hook was ultimately just creating an instance of a Kleisli and returning, without ever actually shutting down the `Server`. This PR corrects that by calling `shutdown` directly on the gRPC `Server`, rather than calling the [`shutdown`](https://github.com/frees-io/freestyle-rpc/compare/master...tyler-clark:shutdown-hook?expand=1#diff-a5d70a63524b8e083da32f9f9c93ca3cR52) method defined within the same class.
> fixing shutdown hook to run shutdown of server

- modules/internal/src/main/scala/encoders.scala
- modules/internal/src/main/scala/util/BigDecimalUtil.scala
- modules/internal/src/test/scala/util/BigDecimalUtilTest.scala
- modules/server/src/test/scala/protocol/RPCTests.scala
- modules/server/src/test/scala/protocol/Utils.scala
Fixes #239 by providing serializers for `scala.math.BigDecimal`
> Adds support for Marshalling/Unmarshalling BigDecimals

- modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
This is the solution that I've found for generating code from IDL present in jar files and submodules and you're running an application (or generating a fat jar).
In the srcJarNames you need to specify not only the jars but also the submodule names that contain the IDL files.
Potentially, we'd need to change the setting name for something like srcIdlNames or something like that. This also filters the files copied to srcGenSourceFromJarsDir, so probably we wouldn't need the mappings in (Compile, packageBin) ~= { _.filter(!_._1.getName.endsWith(".class")) } filter anymore.
Thoughts?
> Allows generating code from IDL in jars and submodules

- modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/build.sbt
- modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromJars/build.sbt
... from the `ProjectPlugin` which it seems to not be needed.
> Removes the IDL core Dependency

- modules/internal/src/main/scala/encoders.scala
- modules/internal/src/test/scala/util/BigDecimalUtilTest.scala
- modules/server/src/test/scala/protocol/RPCBigDecimalTests.scala
- modules/server/src/test/scala/protocol/RPCTests.scala
- modules/server/src/test/scala/protocol/Utils.scala
Provides `BigDecimal` serialization in protobuf and avro.
In the case of avro, I've created the `SchemaFor`, `FromValue`, and `ToValue` instances that will be used in the shapeless derivation of case classes in avro4s. 
Also, a `Marshaller` is provided in avro for serializing `BigDecimal`s as requests and/or responses because Avro doesn't provide the automatic derivation of `FromRecord` and `ToRecord` instances for other types than products.
> BigDecimal serialization in protobuf and avro

- modules/internal/src/main/scala/util/JavaTimeUtil.scala
- modules/internal/src/test/scala/util/BigDecimalUtilTests.scala
- modules/internal/src/test/scala/util/JavaTimeUtilTest.scala
- modules/internal/src/test/scala/util/JavaTimeUtilTests.scala
- project/ProjectPlugin.scala
Adds a serializer for `LocalDate` and `LocalDateTime` more aligned with the `avro` docs:
* `LocalDate` <-> `Int`
* `LocalDateTime` <-> `Long`
> Adds a java time util for serializing dates

- .sbtopts
- project/ProjectPlugin.scala
Updating to this version includes support for `decimal` logical type in avro using `BigDecimal`.
> Bump avrohugger to 1.0.0-RC9

- project/ProjectPlugin.scala
This PR updates:
- `avro4s` to `1.9.0`
- `avrohugger` to `1.0.0-RC10`
These updates include fixes for `decimal` logical type with default values and support for `date` logical type.
> Update avro4s and avrohugger

- modules/server/src/test/scala/fs2/RPCTests.scala
- modules/server/src/test/scala/protocol/RPCTests.scala
Until #164 is fixed. 
Also re-activating a non-FS2 test which may have been ignored by mistake (#237).
> Ignoring new bidirectional FS2 tests on Travis

- modules/examples/routeguide/client/src/main/scala/ClientProgram.scala
- modules/examples/routeguide/client/src/main/scala/handlers/RouteGuideClientHandler.scala
- modules/examples/todolist/client/src/main/scala/clients/PingPongClient.scala
- modules/examples/todolist/client/src/main/scala/clients/TagClient.scala
- modules/examples/todolist/client/src/main/scala/clients/TodoItemClient.scala
- modules/examples/todolist/client/src/main/scala/clients/TodoListClient.scala
- modules/examples/todolist/client/src/main/scala/handlers/PingPongClientHandler.scala
- modules/examples/todolist/client/src/main/scala/handlers/TagClientHandler.scala
- modules/examples/todolist/client/src/main/scala/handlers/TodoItemClientHandler.scala
- modules/examples/todolist/client/src/main/scala/handlers/TodoListClientHandler.scala
- modules/server/src/main/scala/GrpcServer.scala
- modules/server/src/main/scala/handlers/GrpcServerHandler.scala
- modules/server/src/test/scala/protocol/Utils.scala
~Currently, most of the implementaitions only needed the `Handler[F]`
type in the companion.~ Not even that :)
FIXES #292
> replace all occurrences of @tagless annotation with the manual impl

- modules/internal/src/main/scala/client/monixCalls.scala
- project/ProjectPlugin.scala
bring the listenableFuture2Async function to the project, and don't
use frees-async-* packages
FIXES #297
> decouple from frees-async

- docs/src/main/tut/core-concepts.md
- docs/src/main/tut/metrics-reporting.md
- docs/src/main/tut/patterns.md
- modules/config/src/main/scala/client/ChannelConfig.scala
- modules/config/src/main/scala/config.scala
- modules/config/src/main/scala/server/ServerConfig.scala
- modules/config/src/test/scala/server/ServerConfigTests.scala
- modules/examples/routeguide/client/src/main/scala/runtime/ClientConf.scala
- modules/examples/routeguide/server/src/main/scala/implicits.scala
- modules/examples/todolist/client/src/main/scala/implicits.scala
- modules/examples/todolist/server/src/main/scala/implicits.scala
- project/ProjectPlugin.scala
- project/plugins.sbt
In this PR I:
- create a bare minimum `ConfigM` tagless to be used wherever `freestyle.tagless.config` were used before
- remove a couple of `@module` annotations
- bump `frees-todolist-lib`to `v0.8.1`
- bump sbt-freestyle to `0.3.23`
FIXES #294
> Decouple frees config

- project/ProjectPlugin.scala
- version.sbt
This PR downgrades `avro4s` to `1.8.3`, but keeps `avrohugger` up to date, so `decimal` and `date` types continue working.
This downgrade is necessary to until issue #288 is solved.
It also sets freestyle-rpc version to `0.13.6`
> Downgrade avro4s to 1.8.3

- docs/src/main/tut/core-concepts.md
- docs/src/main/tut/metrics-reporting.md
- docs/src/main/tut/patterns.md
- modules/examples/todolist/protocol/src/main/scala/TagProtocol.scala
- modules/examples/todolist/protocol/src/main/scala/TodoItemProtocol.scala
- modules/examples/todolist/protocol/src/main/scala/TodoListProtocol.scala
- modules/internal/src/main/scala/service.scala
- modules/internal/src/main/scala/util/ScalametaUtil.scala
- project/ProjectPlugin.scala
Fixes https://github.com/frees-io/freestyle-rpc/issues/293
Fixes https://github.com/frees-io/freestyle-rpc/issues/295
This PR completes the work removing all the freestyle dependencies from `frees-rpc`, as part of the #290  milestone. It copies from [Freestyle](https://github.com/frees-io/freestyle/blob/8d6366a8383a22737daea9fc325e6d4f111df27f/modules/core/shared/src/main/scala/freestyle/free/internal/ScalametaUtil.scala#L26-L29) the `isAbstract` utility, in order to complete the decoupling.
> Decouples frees-async-cats-effect

- modules/prometheus/client/src/test/scala/BaseMonitorClientInterceptorTests.scala
- modules/prometheus/server/src/test/scala/BaseMonitorServerInterceptorTests.scala
- project/ProjectPlugin.scala
This version is using `cats-effect` `0.10.x`, aligned with the current `cats-effect` version used in frees-rpc.
This is needed until the new monix version is released.
> Upgrades monix to 3.0.0-RC1.

- build.sbt
- modules/client-cache/src/main/scala/ClientCache.scala
- project/ProjectPlugin.scala
> Add client chache sub project

- modules/internal/src/main/scala/service.scala
- modules/server/src/test/scala/protocol/RPCProtoProducts.scala
- version.sbt
Fixes #285 
Thanks to @btlines that pointed me in the right direction (see https://github.com/btlines/pbdirect/issues/21)
> To serialise Option correctly you need to import cats.implicits._ or more specifically import cats.instances.option._. (I suppose you have this import clause present in your tests somehow).
> 
> The reason is that pbdirect knows how to serialise a functor but for this to work it needs an evidence that Option is a Functor and this is provided by importing cats implicits.
> Fixes options and lists serialization in proto

- README.md
- docs/src/main/tut/core-concepts.md
- docs/src/main/tut/idl-generation.md
- modules/internal/src/main/scala/encoders/avro.scala
- modules/marshallers/jodatime/src/main/scala/jodaTimeEncoders.scala
- modules/marshallers/jodatime/src/main/scala/util/JodaTimeUtil.scala
- modules/marshallers/jodatime/src/test/scala/RPCJodaLocalDateTests.scala
- modules/marshallers/jodatime/src/test/scala/RPCJodaLocalDateTimeTests.scala
- modules/server/src/test/scala/protocol/RPCBigDecimalTests.scala
- modules/server/src/test/scala/protocol/RPCJavaTimeTests.scala
- version.sbt
And moves the marshaller instances to its own object.
> Updates docs with the custom codecs section

- README.md
I belive this should be documented, same as in https://github.com/frees-io/freestyle/blob/master/README.md#freestyle-artifacts
> document mandatory compiler plugin

- benchmarks/src/main/scala/AvroBenchmark.scala
- benchmarks/src/main/scala/ProtoBenchmark.scala
- benchmarks/src/main/scala/Utils.scala
- benchmarks/src/main/scala/shared/PersistenceService.scala
- benchmarks/src/main/scala/shared/PersonServiceAvro.scala
- benchmarks/src/main/scala/shared/PersonServicePB.scala
- benchmarks/src/main/scala/shared/Runtime.scala
- benchmarks/src/main/scala/shared/database.scala
- benchmarks/src/main/scala/shared/models.scala
- benchmarks/src/main/scala/shared/server/RPCAvroServer.scala
- benchmarks/src/main/scala/shared/server/RPCProtoServer.scala
- benchmarks/src/main/scala/shared/server/ServerHandler.scala
- build.sbt
- project/plugins.sbt
Related to https://github.com/frees-io/freestyle-rpc/issues/228
This PR brings some benchmarks for unary services based on `Avro` and `Protobuf`. A big part of the code in this PR has been extracted from https://github.com/47deg/metrifier.
> Benchmarks - Avro and Proto Unary Services

- modules/dropwizard/client/src/test/scala/MonitorClientInterceptorTests.scala
- modules/dropwizard/server/src/test/scala/MonitorServerInterceptorTests.scala
- modules/interceptors/src/main/scala/metrics.scala
- modules/prometheus/client/src/main/scala/ClientMetrics.scala
- modules/prometheus/client/src/test/scala/BaseMonitorClientInterceptorTests.scala
- modules/prometheus/client/src/test/scala/MonitorClientInterceptorTests.scala
- modules/prometheus/client/src/test/scala/NamespaceClientTests.scala
- modules/prometheus/server/src/main/scala/ServerMetrics.scala
- modules/prometheus/server/src/test/scala/BaseMonitorServerInterceptorTests.scala
- modules/prometheus/server/src/test/scala/MonitorServerInterceptorTests.scala
- modules/prometheus/server/src/test/scala/NamespaceServerTests.scala
- modules/prometheus/shared/src/main/scala/Configuration.scala
This PR allows providing externally the namespace for the registered metrics. Example:
```scala
val configList: List[ManagedChannelConfig] =
AddInterceptor(
MonitoringClientInterceptor(
Configuration
.defaultAllMetrics
.withCollectorRegistry(CR)
.withNamespace("custom_namespace")
)
)
```
`.withNamespace("custom_namespace")` is the combinator added here. If it's not provided, by default will be `grpc`, the same used until now.
> Allows Custom namespace for server/client metrics

- build.sbt
- modules/idlgen/core/src/test/scala/AvroScalaGeneratorArbitrary.scala
- project/ProjectPlugin.scala
- project/build.properties
This PR bumps up the dependency except the ones related to `cats-effect` which has binary incompatibilities with the latest monix release (we still need to wait for the 3.0.0 final release).
At `sbt` level, I'm upgrading to `1.2.3`, where the `ScriptedPlugin` is no longer auto-triggered. Also, from sbt `1.2.0`, specifying `enablePlugins(SbtPlugin)` enables by default the scripted tests and the setting `sbtPlugin := true`.
> Upgrades Build Dependencies

- modules/internal/src/main/scala/encoders/avro.scala
- modules/internal/src/main/scala/encoders/pbd.scala
- modules/internal/src/main/scala/util/JavaTimeUtil.scala
- modules/internal/src/test/scala/util/JavaTimeUtilTests.scala
- modules/server/src/test/scala/protocol/RPCJavaTimeTests.scala
Fixes #381
It uses the current `LocalDateTime` serializers, since those go from `LocalDateTime` to `Instant` and then to `Long`.
> Adds the avro and protobuffer serializers for java.time.Instant

- version.sbt
This PR proposes to release a new minor version of `frees-rpc`: *0.15.0*. It's a minor version due to some breaking changes introduced in the last merged PRs.
> Releases 0.15.0 frees-rpc Version

- docs/src/main/tut/core-concepts.md
- docs/src/main/tut/idl-generation.md
- modules/idlgen/core/src/main/scala/Model.scala
- modules/idlgen/core/src/main/scala/SrcGenApplication.scala
- modules/idlgen/core/src/main/scala/avro/AvroSrcGenerator.scala
- modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
- modules/internal/src/main/scala/encoders/avro.scala
- modules/server/src/test/scala/protocol/RPCBigDecimalTests.scala
- project/ProjectPlugin.scala
> Adds support for BigDecimal tagged types

- version.sbt
This PR release `mu` **0.16.0**.
It publishes the same binary artifacts as `0.15.1`, but in this case using the new project name.
> Releases 0.16.0

- modules/server/src/main/scala/GrpcServer.scala
Not sure why I did a `F.liftIO(IO.async(...))` in my last pr. Instead I've just changed this to use `F`'s `async` method instead of `IO`.
> No need to liftIO in GrpcServer

- docs/src/main/tut/annotations.md
- docs/src/main/tut/core-concepts.md
- docs/src/main/tut/decimal-migration-guide.md
- docs/src/main/tut/idl-generation.md
- docs/src/main/tut/index.md
- docs/src/main/tut/metrics-reporting.md
- docs/src/main/tut/patterns.md
- docs/src/main/tut/references.md
- docs/src/main/tut/ssl-tls.md
- docs/src/main/tut/streaming.md
… dependent libraries to installation section.
First stab at addressing #474.
> Docs update

- modules/internal/src/main/scala/client/fs2Calls.scala
- modules/internal/src/main/scala/server/fs2Calls.scala
- modules/internal/src/main/scala/service.scala
- modules/server/src/test/scala/fs2/RPCTests.scala
- project/ProjectPlugin.scala
`fs2-grpc` doesn't have support for compression at the server level.  A PR was submitted for addressing that: https://github.com/fiadliel/fs2-grpc/pull/42.
The fs2 support is still experimental so, IMO we're fine.
> Uses fs2-grpc for the fs2 integration

- docs/src/main/tut/decimal-migration-guide.md
- docs/src/main/tut/idl-generation.md
- modules/idlgen/core/src/main/scala/SrcGenApplication.scala
- modules/idlgen/core/src/main/scala/avro/AvroSrcGenerator.scala
- modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
> Defaults to ScalaBigDecimalTaggedGen in the idl-plugin

- benchmarks/shared/src/main/scala/AvroBenchmark.scala
- benchmarks/shared/src/main/scala/AvroWithSchemaBenchmark.scala
- benchmarks/shared/src/main/scala/ProtoBenchmark.scala
- docs/src/main/tut/core-concepts.md
- docs/src/main/tut/metrics-reporting.md
- docs/src/main/tut/patterns.md
- docs/src/main/tut/ssl-tls.md
- modules/client-netty/src/main/scala/netty.scala
- modules/examples/routeguide/client/src/main/scala-io/implicitsio.scala
- modules/examples/routeguide/client/src/main/scala-task/implicitstask.scala
- modules/examples/routeguide/client/src/main/scala/handlers/RouteGuideClientHandler.scala
- modules/examples/todolist/client/src/main/scala/handlers/PingPongClientHandler.scala
- modules/examples/todolist/client/src/main/scala/handlers/TagClientHandler.scala
- modules/examples/todolist/client/src/main/scala/handlers/TodoItemClientHandler.scala
- modules/examples/todolist/client/src/main/scala/handlers/TodoListClientHandler.scala
- modules/examples/todolist/client/src/main/scala/implicits.scala
- modules/idlgen/core/src/main/scala/SrcGenApplication.scala
- modules/internal/src/main/scala/service.scala
- modules/prometheus/client/src/test/scala/InterceptorsRuntime.scala
- modules/prometheus/server/src/test/scala/InterceptorsRuntime.scala
- modules/server/src/test/scala/avro/RPCTests.scala
- modules/server/src/test/scala/avro/Utils.scala
- modules/server/src/test/scala/fs2/Utils.scala
- modules/server/src/test/scala/protocol/RPCTests.scala
- modules/server/src/test/scala/protocol/Utils.scala
- modules/ssl/src/test/scala/RPCTests.scala
Go from this
To this
The problems:
* We can't have nonrequest methods. Not a big deal, I haven't seen rpc services with custom methods.
* The autogenerated clients are not `AbstractStub` from the user perspective. They can always make a casting. If this can be a problem, one alternative could be this #492
Thoughts?
> Makes the client extends the service

- modules/client/src/main/scala/ManagedChannelInterpreter.scala
- modules/client/src/main/scala/package.scala
- modules/client/src/test/scala/ManagedChannelInterpreterTests.scala
- modules/examples/todolist/protocol/src/main/scala/TodoItemProtocol.scala
- modules/internal/src/main/scala/service.scala
- modules/server/src/test/scala/fs2/Utils.scala
This PR separates the `ManagedChannelInterpreter` class from the package object and removes the redundant parameters from its methods.
> Improve managed channel interpreter

- modules/legacy-avro-decimal/procotol/src/main/resources/legacyAvroDecimalCompatProtocol.avdl
Needs to be the same as https://github.com/higherkindness/mu/blob/da0daaf3099297b62d6310e444294e46ac0bc2bd/modules/legacy-avro-decimal/model/src/main/scala/higherkindness/mu/rpc/protocol/legacy/AvroDecimalCompat.scala#L17
> Fixes the avro decimal compat protocol namespace

- benchmarks/shared/src/main/scala/higherkindness/mu/rpc/benchmarks/AvroBenchmark.scala
- benchmarks/shared/src/main/scala/higherkindness/mu/rpc/benchmarks/AvroWithSchemaBenchmark.scala
- benchmarks/shared/src/main/scala/higherkindness/mu/rpc/benchmarks/ProtoBenchmark.scala
- benchmarks/shared/src/main/scala/higherkindness/mu/rpc/benchmarks/shared/server/ServerHandler.scala
- docs/src/main/tut/metrics-reporting.md
- docs/src/main/tut/patterns.md
- docs/src/main/tut/ssl-tls.md
- modules/examples/routeguide/server/src/main/scala/ServerAppIO.scala
- modules/examples/todolist/protocol/src/main/scala/PingPongProtocol.scala
- modules/examples/todolist/protocol/src/main/scala/TagProtocol.scala
- modules/examples/todolist/protocol/src/main/scala/TodoItemProtocol.scala
- modules/examples/todolist/server/src/main/scala/ServerApp.scala
- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/service/GRPCServiceDefBuilder.scala
- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/serviceImpl.scala
- modules/internal/src/test/scala/higherkindness/mu/rpc/internal/GRPCServiceDefBuilderTests.scala
- modules/marshallers/jodatime/src/test/scala/higherkindness/mu/rpc/protocol/RPCJodaLocalDateTests.scala
- modules/marshallers/jodatime/src/test/scala/higherkindness/mu/rpc/protocol/RPCJodaLocalDateTimeTests.scala
- modules/prometheus/client/src/test/scala/higherkindness/mu/rpc/prometheus/client/InterceptorsRuntime.scala
- modules/prometheus/server/src/test/scala/higherkindness/mu/rpc/prometheus/server/InterceptorsRuntime.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/CommonUtils.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/avro/RPCTests.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/fs2/Utils.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/RPCBigDecimalTests.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/RPCJavaTimeTests.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/RPCProtoProducts.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/Utils.scala
- modules/ssl/src/test/scala/higherkindness/mu/rpc/ssl/Utils.scala
- modules/testing/src/main/scala/higherkindness/mu/rpc/testing/servers.scala
- project/ProjectPlugin.scala
This PR makes the `bindService` an effect. It also simplifies the server channel utility in testing, making it a resource. The client builder was migrated to a `Resource` so there is no need to close it.
Let me know.
> `bindService` as an Effect

- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/metrics/MetricsOps.scala
I propose the following interceptors. The `recordHeadersTime` will be only used by the clients since the server doesn't receive headers.
Fixes #512
```scala
package higherkindness.mu.rpc.prometheus.server
import higherkindness.mu.rpc.interceptors.GrpcMethodInfo
import io.grpc._
case class MetricsServerInterceptor() extends ServerInterceptor {
override def interceptCall[Req, Res](
call: ServerCall[Req, Res],
requestHeaders: Metadata,
next: ServerCallHandler[Req, Res]): ServerCall.Listener[Req] = {
val method: GrpcMethodInfo = GrpcMethodInfo(call.getMethodDescriptor)
val metricsCall: MetricsServerCall[Req, Res] =
MetricsServerCall[Req, Res](call, method)
MetricsServerCallListener[Req](next.startCall(metricsCall, requestHeaders), method)
}
}
case class MetricsServerCall[Req, Res](serverCall: …
```
> Defines the MetricsOps algebra

- project/ProjectPlugin.scala
- project/plugins.sbt
This PR overrides the default behavior provided by org-policies. Instead, when Travis is succeeded:
* Release
* Update docs files
* Publish microsite
> Disables dependencies plugin

- modules/metrics/dropwizard/src/main/scala/metricsops/DropWizardMetricsOps.scala
- modules/metrics/dropwizard/src/test/scala/metricsops/DropWizardMetricsOpsTests.scala
The problem was in the metrics name associated to the timers for the method and statuses. When the method type was `UNKNOWN` and the status `Unknown`, both calls were producing the same metrics, consequently, we were getting the expected count multiplied by 2.
Adding the prefix `-methods` and `-statuses` fix the problem and it's also more aligned with the http4s metric naming.
I've added some other tweaks to the current test implementation, feel free to take whatever you like.
> Minor tweaks on the current implementation

- modules/metrics/dropwizard/src/main/scala/metricsops/DropWizardMetricsOps.scala
This pull request fixes a typo in the documentation about the Dropwizard metrics. The messages sent and received were including the `methodType` in the metric name, but we weren't including that info in the implementation.
> Fixes typo in the documentation of Dropwizard metrics

- build.sbt
- docs/src/main/tut/metrics-reporting.md
- modules/channel/src/main/scala/higherkindness/mu/rpc/channel/metrics/MetricsChannelInterceptor.scala
- modules/metrics/dropwizard/src/main/scala/higherkindness/mu/rpc/dropwizard/DropWizardMetrics.scala
- modules/metrics/dropwizard/src/test/scala/higherkindness/mu/rpc/dropwizard/DropWizardMetricsOpsTests.scala
- modules/metrics/prometheus/src/main/scala/higherkindness/mu/rpc/prometheus/PrometheusMetrics.scala
- modules/prometheus/server/src/test/scala/higherkindness/mu/rpc/prometheus/server/InterceptorsRuntime.scala
- modules/server/src/main/scala/higherkindness/mu/rpc/server/interceptors/implicits.scala
- modules/server/src/main/scala/higherkindness/mu/rpc/server/metrics/MetricsServerInterceptor.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/server/metrics/MetricsServerInterceptorTests.scala
- project/ProjectPlugin.scala
This PR:
* Adds a new module that will contain the prometheus metrics impl
* Fixes dropwizard package names
* Moves the interceptor implicits for the server to the server module
> Fixes some package names and some refactors

- build.sbt
- docs/src/main/tut/patterns.md
- modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/SrcGenTests.scala
- modules/internal/src/test/scala/higherkindness/mu/rpc/internal/util/BigDecimalUtilTests.scala
- modules/internal/src/test/scala/higherkindness/mu/rpc/internal/util/EncoderUtilTest.scala
- modules/internal/src/test/scala/higherkindness/mu/rpc/internal/util/JavaTimeUtilTests.scala
- modules/marshallers/jodatime/src/test/scala/higherkindness/mu/rpc/internal/util/JodaTimeUtilTest.scala
- modules/marshallers/jodatime/src/test/scala/higherkindness/mu/rpc/protocol/RPCJodaLocalDateTests.scala
- modules/marshallers/jodatime/src/test/scala/higherkindness/mu/rpc/protocol/RPCJodaLocalDateTimeTests.scala
- modules/metrics/prometheus/src/main/scala/higherkindness/mu/rpc/prometheus/PrometheusMetrics.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/RPCBigDecimalTests.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/RPCJavaTimeTests.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/RPCProtoProducts.scala
- modules/testing/src/test/scala/higherkindness/mu/rpc/testing/MethodsTests.scala
- modules/testing/src/test/scala/higherkindness/mu/rpc/testing/ServersTests.scala
- project/ProjectPlugin.scala
- project/plugins.sbt
This PR:
* Upgrades sbt-org-policies.
* Adds the latest version fo sbt-microsites
* Bumps up some other dependencies like fs2, pbdirect or scalatest, among others.
* The new version of scalatest deprecates some type aliases that I'm replacing for the final version in this PR.
* Adds the `sbt-updates` plugin to be able to run the `dependencyUpdates` command.
> Upgrades Build

- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/serviceImpl.scala
This PR changes the `clientFromChannel` method to use `$F` instead of `F`.
> Macro Fix - Uses $F instead F

- benchmarks/run-benchmark
- benchmarks/run-benchmarks-all
- build.sbt
... in order to be able to compare the current master branch code and the previously released version (0.17.2 in this case).
See https://github.com/higherkindness/mu/tree/master/benchmarks#benchmarks to know more about how to run them.
> Enables benchmarks for the previous Mu version

- modules/server/src/main/scala/higherkindness/mu/rpc/server/GrpcServer.scala
> RPC Server Start with Brackets

- docs/src/main/tut/core-concepts.md
Otherwise the `CommonRuntime` is not shown in the docs.
> CommonRuntime - Converts tut:invisible by tut:silent

- modules/http/src/test/scala/higherkindness/mu/rpc/http/GreeterDerivedRestTests.scala
- modules/http/src/test/scala/higherkindness/mu/rpc/http/GreeterHandlers.scala
- modules/http/src/test/scala/higherkindness/mu/rpc/http/GreeterRestClients.scala
- modules/http/src/test/scala/higherkindness/mu/rpc/http/GreeterRestServices.scala
- modules/http/src/test/scala/higherkindness/mu/rpc/http/GreeterRestTests.scala
- modules/http/src/test/scala/higherkindness/mu/rpc/http/GreeterServices.scala
- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/serviceImpl.scala
- project/ProjectPlugin.scala
> Removes the compatibility of Monix.Observable in the HTTP layer

- version.sbt
Once #481 is merged, we would be able to release **mu 0.18.0** .
> Releases 0.18.0

- build.sbt
- modules/examples/seed/client/modules/app/src/main/resources/application.conf
- modules/examples/seed/client/modules/app/src/main/resources/logback.xml
- modules/examples/seed/client/modules/app/src/main/scala/example/seed/client/app/AvroClientApp.scala
- modules/examples/seed/client/modules/app/src/main/scala/example/seed/client/app/ClientBoot.scala
- modules/examples/seed/client/modules/app/src/main/scala/example/seed/client/app/ClientParams.scala
- modules/examples/seed/client/modules/app/src/main/scala/example/seed/client/app/ProtoClientApp.scala
- modules/examples/seed/client/modules/common/src/main/scala/example/seed/client/common/models.scala
- modules/examples/seed/client/modules/process/src/main/scala/example/seed/client/process/AvroPeopleServiceClient.scala
- modules/examples/seed/client/modules/process/src/main/scala/example/seed/client/process/ProtoPeopleServiceClient.scala
- modules/examples/seed/client/modules/process/src/main/scala/example/seed/client/process/runtime/handlers.scala
- modules/examples/seed/server/modules/app/src/main/resources/application.conf
- modules/examples/seed/server/modules/app/src/main/resources/logback.xml
- modules/examples/seed/server/modules/app/src/main/scala/example/seed/server/app/AvroServerApp.scala
- modules/examples/seed/server/modules/app/src/main/scala/example/seed/server/app/ProtoServerApp.scala
- modules/examples/seed/server/modules/app/src/main/scala/example/seed/server/app/ServerBoot.scala
- modules/examples/seed/server/modules/common/src/main/scala/example/seed/server/common/models.scala
- modules/examples/seed/server/modules/process/src/main/scala/example/seed/server/process/AvroPeopleServiceHandler.scala
- modules/examples/seed/server/modules/process/src/main/scala/example/seed/server/process/ProtoPeopleServiceHandler.scala
- modules/examples/seed/server/modules/protocol_avro/src/main/resources/People.avdl
- modules/examples/seed/server/modules/protocol_avro/src/main/resources/PeopleService.avdl
- modules/examples/seed/server/modules/protocol_avro/src/main/scala/People.scala
- modules/examples/seed/server/modules/protocol_avro/src/main/scala/PeopleService.scala
- modules/examples/seed/server/modules/protocol_proto/src/main/resources/people.proto
- modules/examples/seed/server/modules/protocol_proto/src/main/resources/services.proto
- modules/examples/seed/server/modules/protocol_proto/src/main/scala/people.scala
- modules/examples/seed/server/modules/protocol_proto/src/main/scala/services.scala
- modules/examples/seed/shared/modules/config/src/main/scala/example/seed/config/ConfigService.scala
- project/ProjectPlugin.scala
Add a new sample to Mu based on:
https://github.com/AdrianRaFo/RPC-Avro-Seed
https://github.com/AdrianRaFo/RPC-Proto-Seed
with the minimal client and server on both `avro` and `protobuf`
> Add seed sample

- modules/channel/src/main/scala/higherkindness/mu/rpc/protocol/package.scala
- modules/common/src/main/scala/higherkindness/mu/rpc/protocol/protocol.scala
- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/serviceImpl.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/RPCMethodNameTests.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/RPCNamespaceTests.scala
Relates to #599
This can be considered the first step where we allow to specify a namespace and the ability to capitalize the gRPC method
> Allows specifying the namespace and the capitalize params

- .travis.yml
The command `sbt idlgen-sbt/publish;` fails with the following error:
```
[error] Expected ':'
[error] Not a valid key: release (similar: releaseVcs, releaseVcsSign, releaseProcess)
[error] idlgen-sbt/release
[error]                   ^
```
https://travis-ci.org/higherkindness/mu/jobs/529241748#L584-L587
> Fixes plugin release

- modules/examples/seed/client/modules/process/src/main/scala/example/seed/client/process/AvroPeopleServiceClient.scala
- modules/examples/seed/client/modules/process/src/main/scala/example/seed/client/process/ProtoPeopleServiceClient.scala
- modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala
- project/ProjectPlugin.scala
- Fixes https://github.com/higherkindness/mu/issues/612, having optional fields for non-primitive protobuf fields.
- Added `fs2` prefix to the Stream type of a test, which was also included in this release
> Use updated Skeuomorph version for non-primitive protobuf fields

- modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala
- modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala
- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/serviceImpl.scala
- project/ProjectPlugin.scala
- version.sbt
- The "Cop" regex was not picking up the new Option[A] types
- The "fs2" prefix on Stream was causing the macro to generate the wrong code
> Fix compile errors with the generated source code

- modules/client-cache/src/main/scala/higherkindness/mu/rpc/channel/cache/ClientCache.scala
- modules/client-cache/src/test/scala/higherkindness/mu/rpc/channel/cache/ClientCacheTests.scala
- modules/examples/routeguide/server/src/main/scala/ServerAppIO.scala
client-cache's HostPort type got changed from (String, Int) type to a H type, given by the user. 
Also, one more test has been added. Now it checks two cases: host-port ((String,Int)) channel and hostname (string) channel.
> Issue 563: Client cache should receive a ManagedChannel

- docs/src/main/tut/generate-sources-from-idl.md
- modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/Model.scala
- modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/SrcGenApplication.scala
- modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/avro/AvroSrcGenerator.scala
- modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/package.scala
- modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/AvroScalaGeneratorArbitrary.scala
- modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/SrcGenTests.scala
- modules/idlgen/plugin/src/main/scala/higherkindness/mu/rpc/idlgen/IdlGenPlugin.scala
- modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/gzipCompression/test
- modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/idiomaticEndpoints/build.sbt
- modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/idiomaticEndpoints/project/plugins.sbt
- modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/idiomaticEndpoints/src/main/resources/service.avdl
- modules/idlgen/plugin/src/sbt-test/sbt-mu-idlgen/idiomaticEndpoints/test
Relates to #599
Allows specifying the idiomatic endpoints through a setting key.
It also deprecates `genOptions` and adds a new setting for indicating the compression type.
> Allows generating idiomatic gRPC urls for avro

- docs/src/main/resources/microsite/data/menu.yml
The last release failed to publish the microsite:
```
[info] jekyll 3.2.1 | Error:  (/home/travis/build/higherkindness/mu/docs/target/scala-2.12/resource_managed/main/jekyll/_data/menu.yml): mapping values are not allowed in this context at line 15 column 10
[error] java.lang.RuntimeException: Could not run jekyll, error: 1
[error]     at scala.sys.package$.error(package.scala:26)
[error]     at com.typesafe.sbt.site.jekyll.JekyllPlugin$.generate(JekyllPlugin.scala:49)
[error]     at com.typesafe.sbt.site.jekyll.JekyllPlugin$.$anonfun$jekyllSettings$4(JekyllPlugin.scala:31)
[error]     at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]     at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]     at …
```
> Fixes menu.yml

- docs/src/main/tut/annotations.md
- modules/common/src/main/scala/higherkindness/mu/rpc/protocol/protocol.scala
- modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/ScalaParser.scala
- modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/package.scala
- modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/util/AstOptics.scala
- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/serviceImpl.scala
We use own implementation of Protobuf protocol instead of using PbDirect.
If we specify `Protobuf` as the serialization method in our service definition, we can't use our implementation because `serviceImpl` macro automatically adds the import of PbDirect-specific implementation.
https://github.com/higherkindness/mu/blob/5a8a083e5177aa20e28163fab3a80f4ee1771918/modules/internal/src/main/scala/higherkindness/mu/rpc/internal/serviceImpl.scala#L228-L235
This simple PR adds the possibility to specify the `Custom` serialization type in a service definition. Then we provide own implementation of `io.grpc.MethodDescriptor.Marshaller` for our types and it works!
> Allow specifying custom serialization mechanism

- .travis.yml
- docs/src/main/tut/index.md
- project/ProjectPlugin.scala
* Fixes the tables in the docs
* Execute the tests in the regular builds
* Parallelize the test stage
* Parallelize the deploy stage 
After the commit e0673ffbb68e768192d651cf2ef2c3b090328383, the PRs are not runing the tests. See for example the previous PR build:
* https://travis-ci.org/higherkindness/mu/builds/587708806
And the next one:
* https://travis-ci.org/higherkindness/mu/builds/587777811
> Fixes docs and parallelize some travis jobs

- modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala
- modules/idlgen/core/src/test/resources/proto/streaming_no_shapeless_no.proto
- modules/idlgen/core/src/test/resources/proto/streaming_no_shapeless_yes.proto
- modules/idlgen/core/src/test/resources/proto/streaming_yes_shapeless_no.proto
- modules/idlgen/core/src/test/resources/proto/streaming_yes_shapeless_yes.proto
- modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/AvroSrcGenTests.scala
- modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala
When generating Scala from protobuf files, only add imports for things that are actually referenced in that file.
Also refactor `ProtoSrcGenerator` for consistency with the other generators. It now returns a list of the lines in the generated file instead of a singleton list containing the whole file contents.
TODO in a later PR: pass skeuomorph some kind of flag to tell it whether to use fs2 `Stream` or Monix `Observable` when generating service code.
Fixes #637
> Avoid adding unnecessary imports to generated source files

- modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/avro/AvroSrcGenerator.scala
- project/ProjectPlugin.scala
Bumps avrohugger to 1.0.0-RC22
See https://github.com/julianpeeters/avrohugger/commit/f58bbfb7c2534586d0d781782a9fa96bc3ca3d0c
> Bumps avrohugger to 1.0.0-RC22

- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/encoders/pbd.scala
This ensures we copy the bytes using a buffer for performance. It will also generate less garbage than using `Iterator.continually`.
> Micro-optimisation: use IOUtils to copy InputStream to byte array

- project/ProjectPlugin.scala
This PR fixes the project name (recently renamed to mu-scala).
> Fixes project name

- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/encoders/avro.scala
Simplify the code for parsing an incoming request as Avro.
> Simplify Avro marshaller

- modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala
- modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala
- project/ProjectPlugin.scala
Bump the skeuomorph dependency and use its new scalameta-based printer for source code generation.
> Scalameta codegen

- project/ProjectPlugin.scala
- project/plugins.sbt
Sonatype bundle releases should work with this version of sbt-org-policies, because it brings in a transitive dependency on sbt-sonatype v3.8.1.
Using bundled releases means our artifacts will upload to Sonatype more quickly.
> Upgrade sbt-org-policies and use bundled releases

- build.sbt
This PR prevents to send to Maven central the artifacts related to the health check examples.
> No Publish Healthcheck examples

- modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/Generator.scala
- modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/GeneratorApplication.scala
- modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/avro/AvroSrcGenerator.scala
- modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/openapi/OpenApiSrcGenerator.scala
- modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/proto/ProtoSrcGenerator.scala
- modules/srcgen/core/src/test/scala/higherkindness/mu/rpc/srcgen/AvroScalaGeneratorArbitrary.scala
- modules/srcgen/core/src/test/scala/higherkindness/mu/rpc/srcgen/AvroSrcGenTests.scala
- modules/srcgen/core/src/test/scala/higherkindness/mu/rpc/srcgen/OpenApiSrcGenTests.scala
- modules/srcgen/core/src/test/scala/higherkindness/mu/rpc/srcgen/ProtoSrcGenTests.scala
- modules/srcgen/plugin/src/main/scala/higherkindness/mu/rpc/srcgen/SrcGenPlugin.scala
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/gzipCompression/test
Remove genOptions in sbt-mu-srcgen plugin
> Remove genOptions in sbt-mu-srcgen plugin

- build.sbt
- modules/client-cache/src/test/scala/higherkindness/mu/rpc/channel/cache/ClientCacheTests.scala
- modules/common/src/test/scala/higherkindness/mu/rpc/common/RpcBaseTestSuite.scala
- modules/health-check-unary/src/test/scala/higherkindness/mu/rpc/healthcheck/unary/HealthServiceUnaryTest.scala
- modules/health-check-unary/src/test/scala/higherkindness/mu/rpc/healthcheck/unary/OrderingTest.scala
- modules/internal/src/test/scala/higherkindness/mu/rpc/internal/util/BigDecimalUtilTests.scala
- modules/internal/src/test/scala/higherkindness/mu/rpc/internal/util/EncoderUtilTest.scala
- modules/internal/src/test/scala/higherkindness/mu/rpc/internal/util/JavaTimeUtilTests.scala
- modules/kafka/src/test/scala/higherkindness/mu/rpc/kafka/ServiceSpec.scala
- modules/marshallers/jodatime/src/test/scala/higherkindness/mu/rpc/internal/util/JodaTimeUtilTest.scala
- modules/srcgen/core/src/test/scala/higherkindness/mu/rpc/srcgen/OpenApiSrcGenTests.scala
- modules/streaming/fs2/src/test/scala/higherkindness/mu/rpc/healthcheck/fs2/HealthCheckFS2Test.scala
- modules/streaming/monix/src/test/scala/higherkindness/mu/rpc/healthcheck/monix/HealthCheckMonixTest.scala
- modules/testing/src/test/scala/higherkindness/mu/rpc/testing/MethodsTests.scala
- modules/testing/src/test/scala/higherkindness/mu/rpc/testing/ServersTests.scala
- project/ProjectPlugin.scala
This PR updates to Scalatest 3.1.0, adding the new `scalatestplus-scalacheck` dependency, as it's needed from now on.
> Updates to scalatest 3.1.0

- modules/metrics/prometheus/src/main/scala/higherkindness/mu/rpc/prometheus/PrometheusMetrics.scala
This PR have two goals:
* Easily skip some metric collection. So now you can just send a `None` in some of the metric fields and that metric will be skipped.
* Easily allow to implement the metrics for some call. For example, you can customize the `recordTotalTime` by sending your custom `totalTime` `Histogram` and then `override` the `DefaultPrometheusMetricsOps` class.
The binary compatibility is maintained by keeping the two public methods (`build` and `apply`) untouched.
> Allows custom prometheus metrics collector

- modules/config/src/main/scala/higherkindness/mu/rpc/config.scala
- modules/metrics/prometheus/src/main/scala/higherkindness/mu/rpc/prometheus/PrometheusMetrics.scala
- modules/metrics/prometheus/src/test/scala/higherkindness/mu/rpc/prometheus/PrometheusMetricsTests.scala
Fixes #635
This adds a new builder for construct a prometheus metrics with the service and method names included in the total time histogram.
Since histograms could have some performance problems when the granularity of the labels increase, we can remove the headers histogram from the new builder (which is not providing too much value due to the number of labels). The user could always add their own metrics.
This also provides a sample about how to tune the metric builder.
> Adds a prometheus builder for full metrics

- build.sbt
- docs/src/main/docs/core-concepts.md
- modules/common/src/test/scala/higherkindness/mu/rpc/common/RpcBaseTestSuite.scala
- modules/examples/seed/server/modules/protocol_avro/src/main/scala/People.scala
- modules/examples/todolist/protocol/src/main/scala/TodoListProtocol.scala
- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/encoders/avro.scala
- modules/legacy-avro-decimal/encoders/src/main/scala/higherkindness/mu/rpc/protocol/legacy/avro.scala
- modules/marshallers/jodatime/src/main/scala/higherkindness/mu/rpc/marshallers/jodaTimeEncoders.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/avro/RPCTests.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/avro/Utils.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/RPCMethodNameTests.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/RPCNamespaceTests.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/RPCTests.scala
- modules/srcgen/core/src/test/scala/higherkindness/mu/rpc/srcgen/AvroSrcGenTests.scala
- project/ProjectPlugin.scala
This is mostly mechanical rewrites of the type class instances:
* `ToSchema` -> `SchemaFor`
* `ToValue` -> `Encoder`
* `FromValue` -> `Decoder`
Also slightly rewrote the scale/precision/rounding mode handling in the BigDecimal codecs, in line with the changes in avro4s.
Removed a couple of codecs that are now provided out-of-the-box by avro4s.
Changed the `avroWithSchemaMarshallers` `parse` method to use an `AvroInputStream`. I'm not entirely sure about this change, as I don't know why it was written the way it was before.
> Upgrade to avro4s 3.0.x

- docs/src/main/docs/annotations.md
- docs/src/main/docs/decimal-migration-guide.md
- docs/src/main/docs/ssl-tls.md
- modules/common/src/main/scala/higherkindness/mu/rpc/protocol/protocol.scala
- modules/examples/routeguide/protocol/src/main/scala/Protocols.scala
- modules/examples/seed/server/modules/protocol_proto/src/main/scala/people.scala
- modules/http/src/test/scala/higherkindness/mu/rpc/http/GreeterServices.scala
- modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/avro/AvroSrcGenerator.scala
- modules/srcgen/core/src/test/scala/higherkindness/mu/rpc/srcgen/AvroScalaGeneratorArbitrary.scala
- modules/srcgen/core/src/test/scala/higherkindness/mu/rpc/srcgen/ProtoSrcGenTests.scala
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/basic/src/main/scala/model.scala
- project/ProjectPlugin.scala
It was a relic from the IDL generation feature which has been removed.
> Remove the `@message` annotation

- build.sbt
- docs/src/main/docs/generate-sources-from-idl/avro.md
- docs/src/main/docs/generate-sources-from-idl/index.md
- docs/src/main/docs/generate-sources-from-idl/openapi.md
- docs/src/main/docs/generate-sources-from-idl/proto.md
- modules/srcgen/plugin/src/main/scala/higherkindness/mu/rpc/srcgen/SrcGenPlugin.scala
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/avroWithSchema/build.sbt
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/avroWithSchema/src/main/resources/service.avdl
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/avroWithSchema/test
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/basic/src/main/resources/model.avdl
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/basic/src/main/scala/model.scala
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/basic/test
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/gzipCompression/build.sbt
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/gzipCompression/src/main/resources/service.avdl
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/gzipCompression/test
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/idiomaticEndpoints/build.sbt
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/idiomaticEndpoints/src/main/resources/service.avdl
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/idiomaticEndpoints/test
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/importMarshallers/build.sbt
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/importMarshallers/src/main/resources/service.avdl
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/importMarshallers/test
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcGenFromDirs/build.sbt
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcGenFromDirs/test
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcGenFromJars/build.sbt
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcGenFromJars/test
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcOpenApiGenFromDirs/build.sbt
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcProtoGenFromDirs/build.sbt
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcProtoGenMonix/build.sbt
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcProtoGenMonix/test
I'm working on the documentation at the moment, and noticed this while I was going through a tutorial.
It doesn't really make sense *not* to add the task to the list of sourceGenerators, as the list of generated source files would not be added to `managedSources`. That means even if you ran `muSrcGen` manually and then ran `compile`, the generated source files would not be compiled.
Updated the plugin to automatically register the `muSrcGen` task as a sourceGenerator, and updated the misleading guidance in the documentation.
> Automatically register muSrcGen as a sourceGenerator

- project/ProjectPlugin.scala
Configure sbt to stop sbt recompiling the Scala compiler bridge before every scripted test. This should save us a few seconds of delay between tests.
> Speed up the sbt plugin scripted tests

- .travis.yml
Sbt plugins can only be compiled with Scala 2.12.10. This PR fixes it in the Travis CI pipeline.
> Fixes sbt Plugin Publish

- .travis.yml
- build.sbt
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcProtoGenFromDirs/build.sbt
- modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcProtoGenMonix/build.sbt
This shaves a couple of minutes off the Travis build. The sbt plugin tests are the slowest job in the build.
> Remove unnecessary publishLocal before running scripted tests

- modules/channel/src/main/scala/higherkindness/mu/rpc/channel/ManagedChannelInterpreter.scala
- modules/server/src/main/scala/higherkindness/mu/rpc/server/GrpcServer.scala
Add a method to `GrpcServer` and `ManagedChannelInterpreter` returning a `Resource` for shutting down the server/channel.
> Add methods with Resource to GrpcServer and ManagedChannelInterpreter

- version.sbt
We haven't released in a while, and we are currently blocking people from upgrading to Scala 2.13.
Highlights of this release:
* Scala 2.13 cross-build
* New design for the microsite
* Rewrite the docs
* Automatically register muSrcGen as a sourceGenerator
* [breaking change] Remove the `@message` annotation
* [breaking change] Introduce sum types for `idlType` and `serializationType` sbt settings
* [breaking change] Remove IDL generation feature
* [breaking change] Rename the sbt plugin from `sbt-mu-idlgen` to `sbt-mu-srcgen`
* [breaking change] Rename the sbt plugin's keys for consistency
I'd also like to include #830 in this release. Just waiting for Peter to confirm he is happy to merge it.
> Release 0.21.0

- version.sbt
Because the 0.21.0 release accidentally published only the Scala 2.13 artifacts.
> Release 0.21.1

- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/serviceImpl.scala
Refactors the macro-generated code to avoid generating giant method bodies.
Before the fix, the `@service` macro would generate the following code for the `bindService` method:
```scala
def bindService(...) =
higherkindness.mu.rpc.internal.service.GRPCServiceDefBuilder.build[F](
"fully.qualified.ServiceName",
(FooMethodDescriptor, io.grpc.stub.ServerCalls.asyncUnaryCall(higherkindness.mu.rpc.internal.server.unaryCalls.unaryMethod(algebra.foo, None))),
(BarMethodDescriptor, io.grpc.stub.ServerCalls.asyncUnaryCall(higherkindness.mu.rpc.internal.server.unaryCalls.unaryMethod(algebra.bar, None))),
...
)
```
One tuple is added for each endpoint `Foo`, `Bar`, ... in the service.
The problem is that `FooMethodDescriptor` is a call to a (macro-generated) method which looks like:
```scala
def …
```
> Fix "method too large" error

- docs/src/main/docs/guides/index.md
- docs/src/main/docs/tutorials/index.md
- modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/GeneratorApplication.scala
Currently, the `sbt-mu-srcgen` requires the sbt setting `muSrcGenIdlType` with a value different from the default one: `Unknown`. This happens even for those sbt projects or submodules that have no protocols to generate sources from.
```
Unknown IDL type 'Unknown'. Valid values: Proto, Avro, OpenAPI
```
As a workaround, the user can set up any of the valid values but it's not quite user-friendly.
In this PR, I'm removing the existing validation and changing it by simple check if-else. If the module has a "valid" `muSrcGenIdlType`, the plugin will run the code generator, and, in any other case, the plugin will return an empty list and, an informative message for the user.
Additionally, I'm fixing a couple of broken links in the docs.
> muSrcGenIdlType Tweak

- modules/internal/fs2/src/main/scala/higherkindness/mu/client/fs2Calls.scala
- modules/internal/fs2/src/main/scala/higherkindness/mu/server/fs2Calls.scala
- modules/internal/monix/src/main/scala/higherkindness/mu/server/monixCalls.scala
- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/server/package.scala
- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/server/unaryCalls.scala
- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/serviceImpl.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/fs2/RPCTests.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/fs2/Utils.scala
* Make use of the compression option in `fs2Calls` (it was ignored until now)
* Refactor to pass the compression type as a proper ADT type instead of a string
* Slight tidy-up of the service macro implementation
* Enable compression on client side for compression tests
* Stop using `ConcurrentMonad` type alias in tests because it caused really long lines that messed up the formatting
> Support compression on server side with FS2 streaming

- modules/haskell-integration-tests/mu-haskell-client-server/Setup.hs
- modules/haskell-integration-tests/mu-haskell-client-server/avro-client/Main.hs
- modules/haskell-integration-tests/mu-haskell-client-server/avro-server/Main.hs
- modules/haskell-integration-tests/mu-haskell-client-server/mu-haskell-client-server.cabal
- modules/haskell-integration-tests/mu-haskell-client-server/protobuf-client/Main.hs
- modules/haskell-integration-tests/mu-haskell-client-server/protobuf-server/Main.hs
- modules/haskell-integration-tests/mu-haskell-client-server/protocol/AvroProtocol.hs
- modules/haskell-integration-tests/mu-haskell-client-server/protocol/ProtobufProtocol.hs
- modules/haskell-integration-tests/mu-haskell-client-server/weather.avdl
- modules/haskell-integration-tests/src/main/scala/integrationtest/avro/MyWeatherService.scala
- modules/haskell-integration-tests/src/main/scala/integrationtest/avro/Protocol.scala
- modules/haskell-integration-tests/src/main/scala/integrationtest/protobuf/MyWeatherService.scala
- modules/haskell-integration-tests/src/main/scala/integrationtest/protobuf/Protocol.scala
- modules/haskell-integration-tests/src/test/scala/integrationtest/Constants.scala
- modules/haskell-integration-tests/src/test/scala/integrationtest/HaskellServerRunningInDocker.scala
- modules/haskell-integration-tests/src/test/scala/integrationtest/RunHaskellClientInDocker.scala
- modules/haskell-integration-tests/src/test/scala/integrationtest/avro/HaskellServerScalaClientSpec.scala
- modules/haskell-integration-tests/src/test/scala/integrationtest/avro/ScalaServerHaskellClientSpec.scala
- modules/haskell-integration-tests/src/test/scala/integrationtest/protobuf/HaskellServerScalaClientSpec.scala
- modules/haskell-integration-tests/src/test/scala/integrationtest/protobuf/ScalaServerHaskellClientSpec.scala
* Add Mu-Haskell integration tests that use Avro
* Refactored the integration tests to share Docker-related code between the Avro and Protobuf tests
* Tidy up the Haskell code slightly and apply a formatter
> Avro Mu-Haskell integration tests

- build.sbt
- docs/src/main/docs/guides/grpc-streaming.md
- modules/channel/src/test/scala/higherkindness/mu/rpc/MacroAnnotationCompilationTest.scala
- modules/haskell-integration-tests/src/main/scala/integrationtest/protobuf/MyWeatherService.scala
- modules/haskell-integration-tests/src/main/scala/integrationtest/protobuf/Protocol.scala
- modules/haskell-integration-tests/src/test/scala/integrationtest/protobuf/HaskellServerScalaClientSpec.scala
- modules/http/src/test/scala/higherkindness/mu/rpc/http/GreeterDerivedRestTests.scala
- modules/http/src/test/scala/higherkindness/mu/rpc/http/GreeterHandlers.scala
- modules/http/src/test/scala/higherkindness/mu/rpc/http/GreeterRestServices.scala
- modules/http/src/test/scala/higherkindness/mu/rpc/http/GreeterServices.scala
- modules/internal/fs2/src/main/scala/higherkindness/mu/client/fs2Calls.scala
- modules/internal/fs2/src/main/scala/higherkindness/mu/server/fs2Calls.scala
- modules/internal/monix/src/main/scala/higherkindness/mu/client/monixCalls.scala
- modules/internal/monix/src/main/scala/higherkindness/mu/server/monixCalls.scala
- modules/internal/src/main/scala/higherkindness/mu/rpc/internal/serviceImpl.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/fs2/RPCTests.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/fs2/Utils.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/protocol/Utils.scala
- modules/streaming/fs2/src/main/scala/higherkindness/mu/rpc/healthcheck/fs2/handler/HealthServiceFS2.scala
- modules/streaming/fs2/src/main/scala/higherkindness/mu/rpc/healthcheck/fs2/serviceFS2.scala
- modules/streaming/fs2/src/test/scala/higherkindness/mu/rpc/healthcheck/fs2/HealthCheckFS2Test.scala
- modules/streaming/monix/src/main/scala/higherkindness/mu/rpc/healthcheck/monix/handler/HealthServiceMonix.scala
- modules/streaming/monix/src/main/scala/higherkindness/mu/rpc/healthcheck/monix/serviceMonix.scala
- modules/streaming/monix/src/test/scala/higherkindness/mu/rpc/healthcheck/monix/HealthCheckMonixTest.scala
This is a change to the specification for Mu services. Previously, RPC endpoints with streaming responses were encoded as:
```scala
// with fs2
def foo(req: MyRequest): Stream[F, MyResponse]
// with Monix
def foo(req: MyRequest): Observable[MyResponse]
```
Now we require them to be inside `F[_]`, making them consistent with endpoints that return unary responses. They now look like:
```scala
// with fs2
def foo(req: MyRequest): F[Stream[F, MyResponse]]
// with Monix
def foo(req: MyRequest): F[Observable[MyResponse]]
```
This change is partly for consistency's sake, and mostly because it's required for distributed tracing (see #866 for details).
It's a breaking change for any users who use streaming responses, but the required fix in user code should be pretty small. On the server side, …
> Wrap streaming responses in effect

- project/ProjectPlugin.scala
- project/plugins.sbt
It was used by the sbt-mu-srcgen tests. That module has been moved to
its own repo.
> Remove sbt-scripted plugin

- modules/channel/src/main/scala/higherkindness/mu/rpc/channel/package.scala
- modules/channel/src/test/scala/higherkindness/mu/rpc/channel/metrics/MonitoringChannelInterceptorTests.scala
- modules/kafka/src/main/scala/higherkindness/mu/rpc/kafka/kafkaManagementService.scala
- modules/metrics/dropwizard/src/test/scala/higherkindness/mu/rpc/dropwizard/DropwizardMetricsTests.scala
- modules/metrics/prometheus/src/test/scala/higherkindness/mu/rpc/prometheus/PrometheusMetricsTests.scala
- modules/server/src/main/scala/higherkindness/mu/rpc/server/handlers/GrpcServerHandler.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/server/RpcServerTestSuite.scala
- modules/server/src/test/scala/higherkindness/mu/rpc/server/metrics/MetricsServerInterceptorTests.scala
- modules/testing/src/test/scala/higherkindness/mu/rpc/testing/ServersTests.scala
- project/ProjectPlugin.scala
Use scala-collection-compat to fix deprecation warnings.
> Fix a bunch of compiler warnings

- modules/server/src/main/scala/higherkindness/mu/rpc/server/GrpcServer.scala
Because it had `never` in the initializer, the initialization step would never finish.
Also rewrite the `server` function to use `serverResource`, and add some comments.
> Remove F.never from Resource initializer

- modules/service/src/main/scala/higherkindness/mu/rpc/protocol/protocol.scala
The `@option`, `@outputPackage` and `@outputName` annotations were left over from the old IDL generation feature.
To avoid sbt-mu-srcgen generating code containing `@option` annotations, there is a dependency on:
1. https://github.com/higherkindness/skeuomorph/pull/275 being merged
2. new version of skeuomorph being released
3. sbt-mu-srcgen's skeuomorph dependency being upgraded
> Remove annotations

- modules/server/src/main/scala/higherkindness/mu/rpc/server/handlers/GrpcServerHandler.scala
- modules/tests/src/test/scala/higherkindness/mu/rpc/server/metrics/MetricsServerInterceptorTests.scala
- project/ProjectPlugin.scala
Now that those annotations have been deleted (#908), we can re-enable `-Xfatal-warnings` for Scala 2.13.x.
> Enable -Xfatal-warnings for Scala 2.13

- modules/server/src/main/scala/higherkindness/mu/rpc/server/GrpcServer.scala
- modules/service/src/main/scala/higherkindness/mu/rpc/internal/service/makro/TypeAnalysis.scala
These were triggering `-Xfatal-warnings` and failing the build
> Fix invalid scaladoc

- modules/fs2/src/main/scala/higherkindness/mu/rpc/internal/server/fs2/handlers.scala
- modules/tests/src/test/scala/higherkindness/mu/rpc/http/GreeterDerivedRestTests.scala
Just a small refactoring. I didn't know about the `force` function until now.
> Replace use of Stream.eval(...).flatten with Stream.force

- modules/haskell-integration-tests/README.md
- modules/haskell-integration-tests/mu-haskell-client-server/Dockerfile
- modules/haskell-integration-tests/mu-haskell-client-server/avro-client/Main.hs
- modules/haskell-integration-tests/mu-haskell-client-server/avro-server/Main.hs
- modules/haskell-integration-tests/mu-haskell-client-server/build.sh
- modules/haskell-integration-tests/mu-haskell-client-server/mu-haskell-client-server.cabal
- modules/haskell-integration-tests/mu-haskell-client-server/protobuf-client/Main.hs
- modules/haskell-integration-tests/mu-haskell-client-server/protobuf-server/Main.hs
- modules/haskell-integration-tests/mu-haskell-client-server/protocol/AvroProtocol.hs
- modules/haskell-integration-tests/mu-haskell-client-server/protocol/ProtobufProtocol.hs
- modules/haskell-integration-tests/mu-haskell-client-server/stack.yaml
- modules/haskell-integration-tests/src/test/scala/integrationtest/avro/HaskellServerScalaClientSpec.scala
- modules/haskell-integration-tests/src/test/scala/integrationtest/protobuf/HaskellServerScalaClientSpec.scala
* Upgrade the Mu-Haskell client and server used in the integration tests to v0.3.x.
* Enable some integration tests that were previously `pending`. All tests are now enabled and passing.
* In `stack.yaml`, pin mu-haskell to a git commit (the current `HEAD` of `master`) for now, pending a release of v0.3.1 containing some bugfixes.
* Update the integration tests readme
I've rebuilt the `cb372/mu-haskell-warm-dot-stack` and `cb372/mu-scala-haskell-integration-tests` Docker images on this branch and published them to Dockerhub.
> Upgrade integration tests to Mu-Haskell v0.3

- modules/haskell-integration-tests/mu-haskell-client-server/Dockerfile
- modules/haskell-integration-tests/mu-haskell-client-server/Dockerfile.warm_dot_stack
- modules/haskell-integration-tests/mu-haskell-client-server/build.sh
Update to the `lts-15.5` tag of the `stack-build` image, to match the LTS in `stack.yaml`.
Also convert `warm_dot_stack` to a multi-stage build, in a last ditch attempt to slim down the images enough to run in a GitHub Actions workflow.
> Update base image for integration tests Docker images

- project/ProjectPlugin.scala
According to [grpc v1.30.2](https://github.com/grpc/grpc-java/blob/v1.30.2/build.gradle#L170), the proper version is `2.0.30.Final`.
> Downgrades netty-tcnative-boringssl-static dep

- .github/pull_request_template.md
- microsite/src/main/docs/guides/generate-sources-from-idl/avro.md
- microsite/src/main/docs/guides/generate-sources-from-idl/index.md
- microsite/src/main/docs/guides/generate-sources-from-idl/proto.md
- microsite/src/main/docs/reference/source-generation.md
- microsite/src/main/docs/tutorials/service-definition/avro.md
With this PR (higherkindness/sbt-mu-srcgen#72), we'll need to update the microsite for mu-scala to clarify the correct usage of the sbt-mu-srcgen, since the above change makes it so the plugin is disabled by default and that the users of that plugin will need to update their `build.sbt` files accordingly to take advantage of the new functionality.  
This change is the final piece of the puzzle for this issue: https://github.com/higherkindness/sbt-mu-srcgen/issues/38
> add instructions for manually enabling the sbt-mu-srcgen plugin for versions beyond v0.23.x

- modules/haskell-integration-tests/README.md
- modules/haskell-integration-tests/mu-haskell-client-server/Dockerfile
- modules/haskell-integration-tests/mu-haskell-client-server/Dockerfile.warm_dot_stack
- modules/haskell-integration-tests/mu-haskell-client-server/build.sh
- modules/haskell-integration-tests/mu-haskell-client-server/mu-haskell-client-server.cabal
- modules/haskell-integration-tests/mu-haskell-client-server/stack.yaml
- modules/haskell-integration-tests/src/test/scala/integrationtest/Constants.scala
I've pushed the new images to dockerhub:
- cb372/mu-haskell-warm-dot-stack:lts-16.20
- cb372/mu-scala-haskell-integration-tests:mu-haskell-0.4.0
> Update the integration tests to use mu-haskell v0.4

- modules/haskell-integration-tests/mu-haskell-client-server/protocol/ProtobufProtocol.hs
- modules/haskell-integration-tests/mu-haskell-client-server/stack.yaml
Due to a breaking change required to handle nested types in Protobuf correctly (https://github.com/higherkindness/mu-haskell/pull/260), the integration tests with Haskell need to be updated.
At the same time, some simplification has been done to the `stack.yaml` file, which no longer has to depend on some non-published packages.
> Update Haskell integration tests due to breaking change in Protobuf handling

- modules/haskell-integration-tests/mu-haskell-client-server/Dockerfile
- modules/haskell-integration-tests/mu-haskell-client-server/Dockerfile.warm_dot_stack
- modules/haskell-integration-tests/mu-haskell-client-server/build.sh
- modules/haskell-integration-tests/src/test/scala/integrationtest/Constants.scala
LTS 16.22 and Mu-Haskell 0.4.0.2
> Update the docker images for Haskell integration tests

- microsite/src/main/docs/guides/generate-sources-from-idl/avro.md
- microsite/src/main/docs/reference/source-generation.md
- project/ProjectPlugin.scala
- project/build.properties
This PR updates docs based on https://github.com/higherkindness/sbt-mu-srcgen/pull/159.
Additionally, it upgrades to sbt 1.5.0, removing deprecation warnings related to the old sbt syntax.
> Update docs (sbt-mu-srcgen)

- benchmarks/shared/src/main/scala/higherkindness/mu/rpc/benchmarks/shared/ServerRuntime.scala
- microsite/src/main/docs/guides/custom-grpc-serialization.md
- modules/kafka/src/main/scala/higherkindness/mu/format/AvroWithSchema.scala
- modules/kafka/src/main/scala/higherkindness/mu/kafka/ConsumerStream.scala
- modules/kafka/src/main/scala/higherkindness/mu/kafka/ProducerStream.scala
- modules/service/src/main/scala/higherkindness/mu/rpc/internal/encoders/avro.scala
- modules/tests/src/test/scala/higherkindness/mu/rpc/avro/RPCTests.scala
- modules/tests/src/test/scala/higherkindness/mu/rpc/avro/Utils.scala
- project/ProjectPlugin.scala
Updates all the updatable dependencies to their latest versions, except the ones that involve updating to cats-effect 3.0:
- Update Scala version (this involved a bunch of `nowarn` annotations).
- Update `cats-effect` to `2.5.0`.
- Update organization for `log4cats` (is now under the [Typelevel organization](https://github.com/typelevel/log4cats)).
- Update `avro4s` to `4.0.7` (this involved a few removed parameters and `Decoder` and `Encoder` classes now including the `SchemaFor` (instead of handling it implicitly).
> Update dependencies (avro4s update)

- .scalafmt.conf
- build.sbt
- modules/service/src/main/scala-3/higherkindness/mu/rpc/avro/AvroUnions.scala
- modules/service/src/main/scala-3/higherkindness/mu/rpc/avro/MyUnion.scala
- modules/service/src/main/scala-3/higherkindness/mu/rpc/internal/encoders/avro.scala
- modules/service/src/test/scala-3/higherkindness/mu/rpc/avro/AvroUnionsSpec.scala
- project/ProjectPlugin.scala
Define wrappers for Scala 3 union types, with custom instances of avro4s `SchemaFor`, `Encoder` and `Decoder` to encode them as Avro unions.
e.g. where in Scala 2 we would have used `Int :+: String :+: MyRecord :+: CNil` we can now use `AvroUnion3[Int, String, MyRecord]`.
I've added the unit test to the `service` module for now, which is inconsistent with our practice of collecting all tests in the `tests` module, because it's not possible to cross-build the `tests` module for Scala 3 yet. It has dependencies on a few Scala-2-only modules.
> Define our own Avro union types to replace shapeless Coproduct

- modules/service/src/main/scala-3/higherkindness/mu/rpc/avro/Decimals.scala
- modules/service/src/test/scala-3/higherkindness/mu/rpc/avro/DecimalsSpec.scala
`TaggedDecimal[P <: Int, S <: Int]` is a BigDecimal tagged with the precision and scale extracted from its corresponding `decimal` logical type in the Avro schema.
Implemented as an opaque type, with a smart constructor that performs a couple of sanity checks on the precision and scale of the supplied BigDecimal.
> Add a TaggedDecimal type to replace Shapeless tagging

- project/ProjectPlugin.scala
- project/plugins.sbt
The new version of the srcgen plugin generates code without warnings. This PR bumps the plugin version and restores the `fatal-warnings` option for the scala compiler.
> Restores `fatal-warnings`

- project/ProjectPlugin.scala
Aligns netty-tcnative-boringssl-static version with grpc:
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty
> Bumps Netty SSL (netty-tcnative-boringssl-static)

- build.sbt
- project/ProjectPlugin.scala
- project/build.properties
Closes #1778
Closes #1776
Closes #1775
Closes #1758
> Upgrades scala 2&3 and sbt
