project/ProjectPlugin.scala, project/plugins.sbt
=> Migrates to sbt-freestyle 0.1.0

build.sbt, demo/greeting/src/main/resources/application.conf, demo/greeting/src/main/scala/greeting/GreetingClient.scala, demo/greeting/src/main/scala/greeting/GreetingClientApp.scala, demo/greeting/src/main/scala/greeting/runtime/implicits.scala, demo/http/src/main/resources/application.conf, demo/http/src/main/scala/user/UserClient.scala, demo/http/src/main/scala/user/UserClientApp.scala, demo/http/src/main/scala/user/runtime/implicits.scala, project/plugins.sbt, rpc/src/main/scala/client/ChannelConfig.scala, rpc/src/main/scala/client/package.scala, rpc/src/main/scala/server/ServerConfig.scala, rpc/src/main/scala/server/package.scala
Fixes #17 
This PR adds some logic to be able to load server/client configuration from config files. I'm acquiring a technical debt since for both client/server configurations need to interpret twice. It's something that will be fixed in a separate PR if that makes sense.
=> Server/Channel Configuration

build.sbt, rpc/src/main/scala/server/implicits.scala, rpc/src/test/scala/server/HelperTests.scala, rpc/src/test/scala/server/SyntaxTests.scala, version.sbt
It also releases a new patch version.
=> Adds LoggingM as a part of GrpcServerApp module

build.sbt
Fixes https://github.com/frees-io/freestyle-rpc/issues/59
=> Removes Scalajs badge

README.md, project/plugins.sbt, version.sbt
* Bumps up to `Freestyle` 0.4.1
* Bumps up to `pbdirect` 0.0.5
* Releases a new patch version
* Others
=> Upgrades to the latest version of sbt-freestyle

rpc/src/test/scala/FreesRPCTests.scala, rpc/src/test/scala/Utils.scala
Brings #67 test case.
The test has been tagged as `ignored`.
=> Provides an evidence where #67 shows up

build.sbt
=> Upgrades to gRPC 1.7.0

rpc/src/main/scala/internal/service/service.scala, version.sbt
=> Removes global imports

build.sbt, rpc/src/main/scala/RPCAsyncImplicits.scala, rpc/src/main/scala/client/ChannelConfig.scala, rpc/src/main/scala/client/ChannelM.scala, rpc/src/main/scala/client/handlers/ChannelMHandler.scala, rpc/src/main/scala/client/handlers/TaskMHandler.scala, rpc/src/main/scala/client/implicits.scala, rpc/src/main/scala/client/package.scala, rpc/src/main/scala/internal/client/calls.scala, rpc/src/main/scala/internal/service/service.scala, rpc/src/main/scala/server/GrpcServer.scala, rpc/src/main/scala/server/ServerConfig.scala, rpc/src/main/scala/server/handlers/GrpcServerHandler.scala, rpc/src/main/scala/server/implicits.scala, rpc/src/main/scala/server/package.scala, rpc/src/test/scala/CommonUtils.scala, rpc/src/test/scala/RPCTests.scala, rpc/src/test/scala/TaglessRPCTests.scala, rpc/src/test/scala/TaglessUtils.scala, rpc/src/test/scala/Utils.scala, rpc/src/test/scala/client/ChannelConfigTests.scala, rpc/src/test/scala/client/ImplicitTests.scala, rpc/src/test/scala/server/GrpcServerTests.scala, rpc/src/test/scala/server/ServerConfigTests.scala
Supersedes https://github.com/frees-io/freestyle-rpc/pull/96
=> Upgrades to Freestyle 0.5.0

rpc/src/main/scala/internal/service/service.scala, version.sbt
It also releases `frees-rpc` **0.5.0**.
=> Adds additional SuppressWarnings built-in warts

modules/async/src/main/scala/RPCAsyncImplicits.scala, modules/internal/src/main/scala/service.scala
=> Mini refactoring of `@service`

project/ProjectPlugin.scala, project/plugins.sbt
This PR shouldn't bring any binary change though.
=> Updates build by using sbt-freestyle 0.13.16

project/ProjectPlugin.scala
Upgrades to `0.3.0`, using fs2 `0.10.0-RC2`.
=> Upgrades fs2-reactive-streams lib

project/ProjectPlugin.scala
=> Upgrades to fs2-reactive-streams 0.4.0

modules/internal/src/main/scala/encoders.scala, modules/internal/src/main/scala/service.scala
Played around a bit to get a better understanding what is actually happening in `@service`.
I think this cleans the code up a bit.
=> Refactor service macro

docs/src/main/tut/README.md, modules/server/src/test/scala/fs2/RPCTests.scala, project/ProjectPlugin.scala, project/plugins.sbt
`fs2` streaming considered experimental.
=> Build Upgrade

modules/common/src/main/scala/protocol.scala, modules/internal/src/main/scala/server/fs2Calls.scala, modules/internal/src/main/scala/server/monixCalls.scala, modules/internal/src/main/scala/server/package.scala, modules/internal/src/main/scala/service.scala, modules/server/src/test/scala/fs2/RPCTests.scala, modules/server/src/test/scala/fs2/Utils.scala, modules/server/src/test/scala/protocol/RPCTests.scala, modules/server/src/test/scala/protocol/Utils.scala
As per [this comment](https://github.com/grpc/grpc-java/issues/2196#issuecomment-242141285) seems that this is the right way for enabling compression on the server.
@juanpedromoreno thoughts?
=> Allows adding compression at method level

project/ProjectPlugin.scala, version.sbt
- Update fs2-reactive-streams to 0.5.1
- Release v0.11.1
=> Update fs2-reactive-streams and release 0.11.1

modules/internal/src/main/scala/encoders.scala, project/ProjectPlugin.scala, project/build.properties, project/plugins.sbt
This PR upgrades to Sbt 1.1.1 and also, it bumps up the project dependencies.
=> Project Upgrade

project/ProjectPlugin.scala, project/plugins.sbt
Most changes involve removing repetition from settings provided by `sbt-org-policies` via `sbt-freestyle`. See inline comments for explanations.
=> sbt build config refactoring, with dependency updates

.travis.yml
Fixes:
* Cross-scala publish task
* Adds the task to publish snapshot version of the sbt-plugin.
=> Fixes Snapshot Publish

version.sbt
This release brings, among others things the following patches, features, and additions:
* Fixed stacktraces in tests caused by unclosed channels: https://github.com/frees-io/freestyle-rpc/pull/189
* Upgrades to Freestyle 0.8.0: https://github.com/frees-io/freestyle-rpc/pull/193
* [Docs] Split into different sections: https://github.com/frees-io/freestyle-rpc/pull/190
* Sbt build config refactoring, with dependency updates: https://github.com/frees-io/freestyle-rpc/pull/188
* Merge https://github.com/frees-io/sbt-freestyle-protogen into the `freestyle-rpc` codebase, and update `@rpc` processing to handle latest `freestyle-rpc` syntax: https://github.com/frees-io/freestyle-rpc/pull/184
* Avro IDL support: https://github.com/frees-io/freestyle-rpc/pull/195
Thanks @L-Lavigne, @eperinan and …
=> Releases frees-rpc 0.12.0

docs/src/main/tut/core-concepts.md, docs/src/main/tut/ssl-tls.md, docs/src/main/tut/streaming.md
This PR solves encoding issues related to `###` in docs.
=> Solves encoding issues in docs

version.sbt
Featuring the new Scala generation from Avro (#210)
=> Release 0.13.0

build.sbt, modules/examples/routeguide/client/src/main/scala/Client.scala, modules/examples/routeguide/protocol/src/main/scala/Protocol.scala, modules/examples/routeguide/server/src/main/scala/Server.scala, modules/examples/routeguide/service/src/main/scala/Service.scala
Create an empty structure for the samples and the modules for the first one
=> Create example structure

version.sbt
This release mainly brings support for `AvroWithSchema` serialization type. See changelog/release tag for deeper information.
=> Releases Freestyle RPC 0.13.2

build.sbt, modules/examples/routeguide/server/src/main/resources/application.conf, modules/examples/routeguide/server/src/main/resources/logback.xml, modules/examples/routeguide/server/src/main/resources/route_guide_db.json, modules/examples/routeguide/server/src/main/scala/handlers/RouteGuideServiceHandler.scala, modules/examples/routeguide/server/src/main/scala/io/ServerAppIO.scala, modules/examples/routeguide/server/src/main/scala/io/ServerIO.scala
This pr adds the server module to the route guide example
The server module contains a server with Task and Freestyle-RPC
Fixes: #220
=> Create example route guide server module

docs/src/main/tut/idl-generation.md, modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/build.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromJars/build.sbt
=> Code Generation from IDL definitions placed in different sources

modules/examples/todolist/client/src/main/scala/ClientApp.scala, modules/examples/todolist/client/src/main/scala/ClientProgram.scala, modules/examples/todolist/client/src/main/scala/clients/PingPongClient.scala, modules/examples/todolist/client/src/main/scala/clients/TagClient.scala, modules/examples/todolist/client/src/main/scala/handlers/PingPongClientHandler.scala, modules/examples/todolist/client/src/main/scala/handlers/TagClientHandler.scala, modules/examples/todolist/client/src/main/scala/implicits.scala, modules/examples/todolist/protocol/src/main/scala/PingPongProtocol.scala, modules/examples/todolist/protocol/src/main/scala/Protocols.scala, modules/examples/todolist/protocol/src/main/scala/TagProtocol.scala, modules/examples/todolist/server/src/main/scala/handlers/TagRpcServiceHandler.scala, modules/examples/todolist/server/src/main/scala/implicits.scala, project/ProjectPlugin.scala, project/plugins.sbt
Manage Tags using RPC service / client.
=> Tag RPC Service

modules/idlgen/plugin/src/main/scala/IdlGenPlugin.scala
Check if the file exists before unzipping it.
Thanks to @dwijnand's good :eyes:.
=> Check if file exists before unzipping in idlgen plugin

build.sbt
This PR prevents publishing the example artifacts.
=> noPublishSettings for RPC examples

modules/internal/src/main/scala/client/package.scala, modules/server/src/test/scala/protocol/RPCTests.scala, modules/server/src/test/scala/protocol/Utils.scala
=> Fix #192 (crash with some server stream transformations)

modules/server/src/test/scala/protocol/RPCTests.scala
=> Re-ignoring failing tests, with reference to new issue

modules/idlgen/core/src/main/scala/avro/AvroSrcGenerator.scala, modules/idlgen/core/src/test/resources/avro/PingPongService.scala, modules/idlgen/core/src/test/resources/avro/PingPongWithSchemaService.scala
Probably not the best implementation but I think this could be a solution
=> Group imports with brackets

project/ProjectPlugin.scala, project/build.properties
This PR bumps up to Scala 2.12.6 and Sbt 1.1.6.
=> Upgrades Scala and Sbt versions

version.sbt
=> Releases 0.13.7

modules/internal/src/main/scala/service.scala
I've created a SupressWarts[A] typeclass with a single method
supressWarts(warts: _*)(a: A) to implement wart supression on several
different language constructs:
- methods (`DefDef`)
- values (`ValDef`)
- classes (`ClassDef`)
Since I'm creating instances of that typeclass for the above mentioned
types, i've left both the typeclass definition and the companion
object inside the def method, but the definition could potentially be
moved outside.
The downside of this implementation is that there's a lot of
boilerplate, but there's no homologue to the `mod""` interpolator for
scalamacros.  I've also thought of implementing the supression on a
structural type `T: {def mods: Modifiers}`, but I find it much more
ugly than current implementation.
=> implement Wart suppression

docs/src/main/tut/idl-generation.md, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/gzipCompression/build.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/gzipCompression/project/build.properties, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/gzipCompression/project/plugins.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/gzipCompression/src/main/resources/service.avdl, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/gzipCompression/test
Adds a new scripted test ensuring the `Gzip` compression feature.
Closes https://github.com/frees-io/freestyle-rpc/issues/332
=> Gzip Compression scripted tests

CHANGELOG.md
=> Update 0.14.0 CHANGELOG

build.sbt, modules/internal/src/main/scala/encoders.scala, modules/internal/src/test/scala/util/EncoderUtilTest.scala, modules/marshallers/jodatime/src/main/scala/jodaTimeEncoders.scala, modules/marshallers/jodatime/src/test/scala/RPCJodaLocalDateTests.scala, modules/marshallers/jodatime/src/test/scala/RPCJodaLocalDateTimeTests.scala
-Adds marshallers for serializing and deserializing joda.time dates
-Also fixes the Scalacheck test in EncoderUtilTest file, adding "forAll".
=> Marshallers for serializing and deserializing joda.time dates

project/ProjectPlugin.scala
I tried to update the `netty-tcnative-boringssl-static` dependency, but it gave me an abstract method error execption.
=> Bumps io.grpc dependency

build.sbt, project/ProjectPlugin.scala, project/plugins.sbt
This PR removes sbt-freestyle of the project, replacing it by sbt-org-policies.
=> Decoupling sbt-freestyle

AUTHORS.md, CHANGELOG.md, CONTRIBUTING.md, NOTICE.md, README.md, docs/src/main/tut/idl-generation.md, docs/src/main/tut/index.md, project/ProjectPlugin.scala, version.sbt
This PR aligns the documentation and project build files with the latest release: 0.15.1.
=> 0.15.1 - Update docs and files 

build.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/avroWithSchema/build.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/avroWithSchema/project/plugins.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/build.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/basic/project/plugins.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/gzipCompression/build.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/gzipCompression/project/plugins.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/importMarshallers/build.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/importMarshallers/project/plugins.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/build.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromDirs/project/plugins.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromJars/build.sbt, modules/idlgen/plugin/src/sbt-test/sbt-frees-rpc-idlgen/srcGenFromJars/project/plugins.sbt, modules/prometheus/client/src/test/scala/BaseMonitorClientInterceptorTests.scala, modules/prometheus/server/src/test/scala/BaseMonitorServerInterceptorTests.scala, modules/server/src/test/scala/fs2/RPCTests.scala, modules/server/src/test/scala/protocol/RPCTests.scala, project/ProjectPlugin.scala
This PR renames `frees.io` by `higherkindness.io`.
_Notice_ the base branch (under the feature branch).
=> Renames groupId

CHANGELOG.md, version.sbt
.. and set up the next snapshot version.
=> Updates 0.16.0 Changelog File

project/ProjectPlugin.scala
=> Update circe deps to latest version

project/ProjectPlugin.scala
Solves #447 #450 #453 #454 #455 #457 #459
=> Update grpc deps to latest version

docs/src/main/tut/core-concepts.md, docs/src/main/tut/decimal-migration-guide.md, docs/src/main/tut/idl-generation.md, docs/src/main/tut/ssl-tls.md
=> Fixes decimal migration guide doc

.travis.yml, build.sbt, project/ProjectPlugin.scala
=> Code Coverage and Codecov support

project/ProjectPlugin.scala
Fixes #411 
Thanks @franciscodr for your fix in avrohugger (https://github.com/julianpeeters/avrohugger/pull/105)
=> Bumps avrohugger

.gitignore
This PR ignores those files generated by [Metals](https://github.com/scalameta/metals).
=> Ignores Metals files

docs/src/main/tut/annotations.md, docs/src/main/tut/core-concepts.md, docs/src/main/tut/decimal-migration-guide.md, docs/src/main/tut/idl-generation.md, docs/src/main/tut/index.md, docs/src/main/tut/metrics-reporting.md, docs/src/main/tut/patterns.md, docs/src/main/tut/references.md, docs/src/main/tut/ssl-tls.md, docs/src/main/tut/streaming.md
=> Removes outdated references to freestyle

build.sbt, modules/channel/src/test/scala/higherkindness/mu/rpc/channel/metrics/MonitoringChannelInterceptorTests.scala, modules/internal/src/test/scala/higherkindness/mu/rpc/internal/metrics/util.scala, modules/server/src/main/scala/higherkindness/mu/rpc/server/metrics/MetricsServerInterceptor.scala, modules/server/src/test/scala/higherkindness/mu/rpc/server/metrics/MetricsServerInterceptorTests.scala
This pull request implements Server Metrics based on MetricOps.
It closes #516
=> Server metrics implementation based on MetricOps

.travis.yml, modules/idlgen/plugin/src/main/scala/higherkindness/mu/rpc/idlgen/IdlGenPlugin.scala
I'll restore the `51` line on snapshot
`sbt ";project idlgen-sbt;release";`
=> Fixes deployment

.travis.yml, build.sbt, docs/src/main/tut/index.md, version.sbt
Also  and publish the legacy protocol with its own command
=> Moves the site publication to a new stage

modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala, project/ProjectPlugin.scala, project/plugins.sbt
This PR closes #578 
Must be in hold for now until having the Skeuomprh change released
=> Adapts latest changes in the code generation by Skeuomorph

docs/src/main/resources/microsite/data/menu.yml, docs/src/main/tut/schema-evolution/avro.md, docs/src/main/tut/schema-evolution/index.md, docs/src/main/tut/schema-evolution/proto.md
Solves https://github.com/higherkindness/mu/issues/335
=> [Docs] Schema Evolution

docs/src/main/tut/schema-evolution/index.md
It'll require to re-deploy the microsite after merge.
=> Fixes schema-evolution links

modules/examples/seed/server/modules/app/src/main/scala/example/seed/server/app/AvroServerApp.scala, modules/examples/seed/server/modules/app/src/main/scala/example/seed/server/app/ProtoServerApp.scala, modules/examples/seed/server/modules/process/src/main/scala/example/seed/server/process/ProtoPeopleServiceHandler.scala, modules/internal/src/main/scala/higherkindness/mu/rpc/internal/metrics/MetricsOps.scala, modules/metrics/dropwizard/src/main/scala/higherkindness/mu/rpc/dropwizard/DropWizardMetrics.scala, modules/metrics/dropwizard/src/test/scala/higherkindness/mu/rpc/dropwizard/DropwizardMetricsTests.scala, modules/metrics/prometheus/src/main/scala/higherkindness/mu/rpc/prometheus/PrometheusMetrics.scala
Remove some unneeded prefixes from the metric labels
=> Improves rpc metrics naming

modules/metrics/prometheus/src/main/scala/higherkindness/mu/rpc/prometheus/PrometheusMetrics.scala, version.sbt
Fixes an issue with the metrics name. It also releases a new patch version
=> Fixes metric prefix

docs/src/main/tut/generate-sources-from-idl.md, modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/SrcGenApplication.scala, modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala, modules/idlgen/core/src/test/scala/higherkindness/mu/rpc/idlgen/ProtoSrcGenTests.scala, project/ProjectPlugin.scala, version.sbt
Bumps skeuomorph and adds support for idiomatic endpoints in proto
=> Support for idiomatic endpoints in protobuf

.travis.yml, build.sbt, modules/streaming/fs2/src/test/scala/higherkindness/mu/rpc/healthcheck/fs2/HealthCheckFS2Test.scala, project/ProjectPlugin.scala, project/build.properties, project/plugins.sbt
It upgrades both Scala 2.12 and Sbt versions to the latest.
=> Upgrades Sbt/Scala

version.sbt
We (@AdrianRaFo and I) would need to have the documentation released for tomorrow's workshop.  The related PR is this one (https://github.com/higherkindness/mu/pull/640)
=> Releases 0.19.0

version.sbt
The new release will include #683 along with some dependency upgrades by @scala-steward .
=> Releases 0.19.1

project/ProjectPlugin.scala
See https://github.com/higherkindness/skeuomorph/pull/184
=> Add a dependency on Enumeratum

version.sbt
Once this has been merged and the automation has done its thing, I'll make another PR to add some notes to the CHANGELOG about the new features and breaking changes.
=> Release v0.20.0

.travis.yml
Makes it easier to understand what Travis is doing.
=> Name the scripts in Travis

CHANGELOG.md, docs/src/main/tut/generate-sources-from-idl/index.md
=> Add release notes for v0.20.0

version.sbt
=> Release 0.20.1

project/ProjectPlugin.scala, version.sbt
=> Bump version number and fix release step

.gitignore, docs/src/main/tut/generate-sources-from-idl/avro.md, docs/src/main/tut/generate-sources-from-idl/index.md, docs/src/main/tut/generate-sources-from-idl/openapi.md, docs/src/main/tut/generate-sources-from-idl/proto.md
This is the documentation update for https://github.com/higherkindness/mu-scala/pull/764
=> Update the documentation for sbt-mu-srcgen key changes

docs/src/main/tut/generate-sources-from-idl/avro.md, docs/src/main/tut/generate-sources-from-idl/index.md, docs/src/main/tut/generate-sources-from-idl/openapi.md, docs/src/main/tut/generate-sources-from-idl/proto.md, modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/Generator.scala, modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/GeneratorApplication.scala, modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/Model.scala, modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/SrcGenApplication.scala, modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/avro/AvroSrcGenerator.scala, modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/avro/package.scala, modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/openapi/OpenApiSrcGenerator.scala, modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/openapi/package.scala, modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/proto/ProtoSrcGenerator.scala, modules/srcgen/core/src/main/scala/higherkindness/mu/rpc/srcgen/proto/package.scala, modules/srcgen/core/src/test/scala/higherkindness/mu/rpc/srcgen/AvroScalaGeneratorArbitrary.scala, modules/srcgen/core/src/test/scala/higherkindness/mu/rpc/srcgen/OpenApiSrcGenTests.scala, modules/srcgen/core/src/test/scala/higherkindness/mu/rpc/srcgen/ProtoSrcGenTests.scala, modules/srcgen/plugin/src/main/scala/higherkindness/mu/rpc/srcgen/SrcGenPlugin.scala, modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/avroWithSchema/test, modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/basic/test, modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/gzipCompression/test, modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/idiomaticEndpoints/test, modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/importMarshallers/test, modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcGenFromDirs/build.sbt, modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcGenFromJars/build.sbt, modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcOpenApiGenFromDirs/build.sbt, modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcProtoGenFromDirs/build.sbt, modules/srcgen/plugin/src/sbt-test/sbt-mu-srcgen/srcProtoGenMonix/build.sbt
=> Introduce sum types for `idlType` and `serializationType`

.travis.yml, build.sbt
The previous PR #818 fixed partially the problem, in this PR I'm making explicit the Scala version used in every sbt session to prevent issues.
=> Explicit scala version in Travis Script

build.sbt, project/ProjectPlugin.scala
Also delete a few unused dependencies
=> Remove sbt-org-policies dependency syntax

project/ProjectPlugin.scala
=> Fix release step to enable cross-publishing

version.sbt
=> Release 0.21.2

version.sbt
Releases a new patch version: 0.21.3
=> Releases 0.21.3

docs/src/main/docs/guides/custom-grpc-serialization.md
=> Clarify and extend the docs about gRPC compression

benchmarks/README.md, benchmarks/run-benchmark, project/ProjectPlugin.scala
Updates the benchmarks docs and the scripts. It also bumps the latest released version of mu.
=> Updates benchmarks docs and scripts

README.md
=> Fix example link in the readme

docs/src/main/docs/guides/ssl-tls.md, docs/src/main/docs/index.md
=> Add a note about the default transport layer in gRPC servers

project/ProjectPlugin.scala
Updates to the [latest and temporary version](https://github.com/47degrees/avro4s/releases/tag/v3.0.10-temp) of avro4s, using a temporary fork.
=> Uses Temporary avro4s Release

project/ProjectPlugin.scala
Back to the [new release version](https://github.com/sksamuel/avro4s/issues/472#issuecomment-623448574).
=> Back to the new avro4s version

docs/src/main/docs/reference/modules-artifacts.md, docs/src/main/docs/reference/source-generation.md
=> Update module names in documentation

modules/kafka/src/main/scala/higherkindness/mu/rpc/kafka/kafkaManagementService.scala, project/ProjectPlugin.scala
=> Bumps pbdirect

.scalafmt.conf, modules/server/src/main/scala/higherkindness/mu/rpc/server/metrics/MetricsServerInterceptor.scala, modules/service/src/main/scala/higherkindness/mu/rpc/channel/metrics/MetricsChannelInterceptor.scala, modules/tests/src/test/scala/higherkindness/mu/rpc/fs2/Utils.scala, modules/tests/src/test/scala/higherkindness/mu/rpc/protocol/Utils.scala
=> Update scalafmt-core to 2.6.0

microsite/src/main/docs/reference/source-generation.md
Closes https://github.com/higherkindness/mu-scala/issues/972
=> updating the muSrcGenStreamingImplementation docs to include the Monix value

project/ProjectPlugin.scala
The dependency is not really used.
=> Removes circe dependency

project/ProjectPlugin.scala
According to the compatibility table
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty
=> Aligns netty-ssl versions

project/ProjectPlugin.scala
Updates to the latest version of the pbdirect library.
=> Updates to pbdirect 0.7.0

.scala-steward.conf, project/ProjectPlugin.scala
According to the compatibility table
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty
=> Aligns netty SSL version

project/ProjectPlugin.scala
According to https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty
Relates to https://github.com/higherkindness/mu-scala/pull/1356
=> Updates SSL Netty

microsite/src/main/docs/guides/grpc-streaming.md
=> Fixed Typo.

microsite/src/main/resources/microsite/data/menu.yml
=> Remove dead link to Compendium-related page

project/ProjectPlugin.scala
Based on 
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty
=> Aligns netty-tcnative-boringssl-static

modules/tests/src/test/scala-2/higherkindness/mu/rpc/fs2/RPCTests.scala, project/ProjectPlugin.scala
Introduce scala retry library to improve the diagnosis of some flaky tests
=> Adds some retries for the flaky tests
